prepare.sh
requirements.txt

Froze versions and formalized package dependencies into `requirements.txt` to help with virtualenv-based development and deployment setups.
For deployment without virtualenv (i.e. single-use VPS setups), running the following is equivalent.
```sh
sudo ./prepare.sh
```

Freeze package + version requirements and changed pip install command

---

CTFd/views.py

Whenever a user submits account data via POST requests to `/profile`, the current password has to be supplied in the "Old Password" titled field. However, when the user omits a "new" password, the password variable will be referenced regardless if it is assigned or not.
In order to make it clear for users where they have to supply a password, additional changes to the `/profile` route are necessary.

Fixed permanent "referenced before assignment" condition

---

CTFd/admin.py
CTFd/challenges.py
CTFd/utils.py
CTFd/views.py
templates/admin/config.html

Add a Config entry `view_challenges_unregistered` to indicate whether
unregistered users can view challenges. Add the setting to the admin config
page.
Add can_view_challenges() to utils to test if a user is either authed, or the
configuration allow unauthenticated users to view the challenges.
Return a HTTP 401 Unauthorized error when the /chals/solves API can't provide
results for an unauthenticated user. This is needed because the client side
code in `chalboard.js` doesn't know if it's logged in or not and requests this
anyway. (And AJAX doesn't handle redirects very well.) Alternately the client
could actually know if they're logged in and not make needless API calls.
When an unregistered user attempts to submit a flag, it will also fail. The
user will be redirected to a login page.

Optionally allow unregistered users to view challenges

---

CTFd/config.py
CTFd/utils.py

Use the `app.config['ADMINS'][0]` address as the from address in Mailgun messages.
TODO: This email address should probably be configurable in the admin settings.
This is a quick fix to not hardcode the address for emails sent via Mailgun. I also must confess I haven't tested this or configured Mailgun yet.
You might want to just set the admin address to <noreply@ctfd.io> on ctfd.io to get the old behavior back.

Fix Mailgun from address

---

CTFd/admin.py
templates/admin/statistics.html

If there is a challenge with zero solves, the current statistics does not include it in the "least solved" statistic (because there is no entry for that challenge in the solves table yet).
This fix will show challenges without solves in the least solved statistic.

fix least solved challenge statistic

---

CTFd/admin.py
CTFd/challenges.py
CTFd/views.py
static/js/chalboard.js
templates/admin/config.html

This allows admin to set a maximum number of attempts per challenge (0 to disable, which is default).
If max attempts is reached, challenge is marked red and displays appropriate error message when more solutions are submitted.

enable max-attempts per challenge setting

---

CTFd/admin.py

Certain POST requests for updating, creating, and deleting challenges were left unauthenticated.

Fix authentication for certain admin actions

---

Dockerfile
docker-compose-run.sh
docker-compose.yml

Containerization of CTFd into gunicorn, Postgres, and data containers for easy backups and upgrades. Can be quickly tested by running:
```
docker-compose build
docker-compose up
```
Data persistence across application source code updates is also tested and working.
`Dockerfile` has been modified to:
* Install `postgresql-dev` and `psycopg2`
* Perform a COPY of the current directory instead of cloning the repo again

Docker Compose containerization

---

CTFd/templates/teams.html
CTFd/views.py

Don't make current page id a link on Teams page

---

CTFd/static/admin/js/team.js
CTFd/templates/admin/team.html

The times and dates were showing "Invalid Date" in the admin view for a team page. This reuses the code from the non-admin template for team (CTFd/templates/team.html).

Fixed time rendering in the team page (admin view)

---

CTFd/static/css/style.css

Buttons would be invisible if they did not have .btn-theme. Now they appear normally :3

Fixed button outlining so that custom buttons do not appear invisible

---

CTFd/__init__.py
CTFd/admin.py
CTFd/models.py
CTFd/templates/admin/pages.html

1.  Fix the deprecation warnings by changing from `flask.ext.$name` to `flask_$name`
The most recent version of flask has deprecated the redirect namespace, so this is just cleanup.  This should only cause compatibility issues if someone is using an *ancient* version of a flask extension (which they shouldn't be, as you recommend using pip to install things).
2.  Be consistent with import style in admin.py
One liner change from #125 so that it's consistent with the rest of the file.  Purely cosmetic.
3.  Fix a residual script_root fix
These keep popping up as my friends do more usability testing.  Again, one liner.
4.  Store IPs in 32 bits again
This is the only potentially breaking change.  Switching it to a 64 bit integer fixed non-SQLite databases (since the SQLAlchemy integer datatype …

Various small fixes

---

CTFd/admin.py

see http://stackoverflow.com/questions/15397680/detaching-sqlalchemy-instance-so-no-refresh-happens
maybe expunge every obj is better,but i'm lazy(so use expunge_all()).

fix DetachedInstanceError on /admin/statistics

---

CTFd/auth.py

it made something like  http://localhost:4000/reset_password/reset_password/Ilx1MzA1NVx1MzA0Zlx1MzA4OVx1ODM1OCIuQ25zSEN3LlVxRlBxUzB4clR6QzdkREdaR2hBLWIzY1FRcw==
it should be http://localhost:4000/reset_password/Ilx1MzA1NVx1MzA0Zlx1MzA4OVx1ODM1OCIuQ25zSEN3LlVxRlBxUzB4clR6QzdkREdaR2hBLWIzY1FRcw==

fix reset_password show twice in reset email

---

CTFd/views.py

Before, `/teams` pagination was broken, because the number of teams being displayed on the page was being interpreted as the total number of teams. Therefore, CTFd would only show the first 50 teams ever, and never display the pagination bar.
This fixes that.

Paginate team page properly

---

docker-compose-run.sh

The variable `i` was not declared and never incremented.
The behaviour was the right one (waiting for MySQL to be listening before starting the application) but was displaying errors.

Fix MySQL availability tries counter

---

CTFd/admin.py
CTFd/templates/original/admin/correct_keys.html
CTFd/templates/original/admin/team.html
CTFd/templates/original/admin/wrong_keys.html

- Fixed wrong_keys.html template using WrongKeys.team instead of
WrongKeys.teamid
- Added the id of the wrong key to the wrong_keys.html template entries
- Changed /admin/wrong_keys to only take the key id instead of team and
challenge id, to allow deleting the intended key when a team has more
than one wrong key for a challenge. (Previously it would delete only
the first wrong key entry for that challenge)

Fix deleting wrong keys from admin panel

---

CTFd/auth.py

When a user attempts to confirm an e-mail address, an exception is thrown because the db session is closed prior to logging.
The line db.session.close() has to move after the logging, otherwise the team parameters from the orm object are discarded and an exception is thrown.
Closing the session after logging, fixes the issue.

Fix exception on cofirmation screen

---

CTFd/templates/admin/teams.html
CTFd/templates/original/teams.html

Team websites starting with https:// are allowed by the URL verification function but are not displayed by the teams templates. This fixes that so https:// team websites are visible on the team list pages.

Fix display of team websites with https:// prefixes

---

Dockerfile

Docker provides some useful resources for Ubuntu as a base image
and installing software via apt-get:
https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#apt-get
It's also useful to pin the Ubuntu version to 16.04 so we have a good
idea of what OS we're using in the image. To that end, I think we can
also avoid performing an upgrade so we can even further control which
versions of software we're using. If we do an upgrade then you'll have
different versions of software depending on when you build the image.

Pin Ubuntu version and follow Dockerfile best practices

---

CTFd/utils.py

`ports_asked` was undefined, this got caught by my auto-linter :)
What do you think about fixing PEP8 errors and adding `pep8` into the build process? Something like:
```
$ pep8 --ignore E501 CTFd/
CTFd/__init__.py:15:1: E302 expected 2 blank lines, found 1
CTFd/__init__.py:44:35: E262 inline comment should start with '# '
CTFd/__init__.py:58:24: E261 at least two spaces before inline comment
CTFd/__init__.py:58:25: E262 inline comment should start with '# '
CTFd/__init__.py:61:78: E261 at least two spaces before inline comment
CTFd/__init__.py:61:79: E262 inline comment should start with '# '
CTFd/auth.py:22:41: E261 at least two spaces before inline comment
CTFd/auth.py:39:45: E261 at least two spaces before inline comment
...
```
It's a cheap way to catch bugs like this, and also to …

Fix undefined variable

---

CTFd/utils.py

Extends get_config to first query config.py for the value. Unsure if the database should come first or not...

improving get_config

---

CTFd/admin/__init__.py
CTFd/templates/admin/config.html
CTFd/utils.py
requirements.txt

This is the beginning of the the import/export feature which allows CTF organizers to backup portions of their CTF and others can add the challenges back into CTFd at a later time. 
The entire database is backed up as JSON and uploads folder is bundled into a zip file. 
Additional thoughts:
* Should the backup file be named .ctf? 
* At the moment CTFd stops on Integrity errors. Should we skip over the bad data and report it to the user?
* Error messages are show to the user in an alert. Should we do something prettier?

Import export

---

CTFd/models.py
CTFd/utils.py

Something in Flask 0.12 changed the behavior of Jinja templates. There
are a couple open issues about it:
https://github.com/pallets/flask/issues/1907

Fixing theme switching

---

CTFd/__init__.py

MySQL can have some issues with unicode because of it's default understand of UTF8 which is like some kind of stunted version of UTF-8. 
Instead we force the charset to be `utf8mb4`.

Changes the default charset for MySQL

---

CTFd/__init__.py
CTFd/admin/__init__.py
CTFd/utils.py
export.py

This fixes #250, #246
Adds export.py to save CTFs without needing to actually spin up CTFd
Also forcing charset properly for MySQL

Upgrading exports

---

README.md

Latest PR moving around the theme files broke the image links in the README.

Fix Image Links in README

---

CTFd/themes/original/static/js/chalboard.js

Previously, there was no way to know what tags were on a challenge on the client-side without making a separate query. This was inconvenient for theme authors who might want to add some styling based on Tags, without needing to insert or modify JS in the middle of the chalboard files.
This will, for instance, allow theme authors to give admins an easy way to customize challenges (imagine a "Hot" set of challenges, moderated by Tags, or challenges sorted on the client-side by tag).
I put the tag on the outermost element for each challenge, though it wouldn't be unreasonable to move it to one of the inner ones.

Add Tags as a CSS class on challenge boxes

---

docker-compose.yml
tests/test_user_facing.py

CTFd creates the database instead of the docker-compose files which allows us to control encoding. Also adds a test for registering with a unicode team name.

Fixes #315

---

CTFd/admin/__init__.py

The `/admin/plugins/<plugin>` route for POST method does not clear the cache after `utils.set_config(k, v)` so the results for `utils.get_config(k)` are not updated immediately.

Clear cache after set config in admin_plugin_config()

---

CTFd/admin/__init__.py

Hi, I just noticed the cache clearing in my PR yesterday called for each key in POST request to `/admin/plugins/<plugin>`. Actually it only needs to be called once.

Only need to clear cache once in admin_plugin_config()

---

CTFd/models.py
CTFd/themes/original/templates/team.html
tests/helpers.py
tests/test_user_facing.py

I noticed that admins were unable to unlock hints. This is because admins effectively got a zero score in terms of the game because admins are banned by default. 
This raises an interesting question that has been raised before, should bans have any effects on users besides hiding from the scoreboard? 
Instead of not getting score if banned, get score for any user, even if they are banned. 
This should come with tests for unlocking hints.

Users should always be able to get their score, even if banned

---

CTFd/themes/admin/templates/config.html
CTFd/utils.py

This cleans up the config.html file a little to remove spaces in favor of tabs for HTML. 
Also change get_smtp to properly support SSL instead of just TLS. This was tested with Google SMTP on port 465 and 587 to make sure we don't regress. 
Also change the username and password inputs for the mailserver config to only appear if the use_mailauth checkbox is checked.

Toggle username_password inputs depending on mail_useauth and clean get_smtp util

---

CTFd/admin/containers.py
CTFd/themes/admin/templates/containers.html
CTFd/utils.py

The current docker builds can time out, even for simple things. This pull request allows the user to do their own "docker build" in the background and then import the image into the database so that it can be launched as needed. By default the image is not launched.

Allow importing of longer-running docker builds

---

CTFd/themes/original/static/js/scoreboard.js

Currently, labels in the scoreboard chart are sorted in lexicographic order.
This PR adds sorting in a way that labels appear in the same order as the top 10 (1st team on top, 10th at the bottom).
The current scoreboard is:
The old way of displaying labels is:
The new way of displaying labels is:

Add sorting of labels in the plotly scoreboard chart

---

CTFd/challenges.py
CTFd/plugins/challenges/__init__.py

First step towards resolving #337. This allows Challenge Plugins/Challenge Types to control the message users see when they try to solve a challenge.

Give challenge plugins the ability to specify the response message

---

development.txt
tests/test_user_facing.py
tests/test_utils.py

Freeze time with freezegun so that tokens for confirming email addresses and verifying teams are constant and then test the behavior properly. 
Perhaps later have a single function to generate these tokens.

Pushing new tests and freezegun

---

CTFd/themes/original/static/js/templates/challenges/standard/standard-challenge-modal.hbs
CTFd/themes/original/templates/base.html
CTFd/themes/original/templates/chals.html
CTFd/utils.py

This is an enhancement to the plugin system to allow a developer to add javascript files to the theme templates. 
This is being done to support an upcoming plugin but it is a useful feature for other plugin developers.

Plugins can register global javascript files

---

CTFd/themes/original/static/js/chalboard.js

This is an old issue that I never really bothered to fix. Apparently `update()` has some issues with data being ready to be rendered by `updateChalWindow()` but with some callbacks and sorting data should be ready to rendered. 
Before the solves tab could display zero solves, but now the solves tab will correctly show the right amount of solves gotten from the `/chals/solves` endpoint.

Call updatesolves on chal update

---

CTFd/admin/pages.py
CTFd/utils.py
CTFd/views.py

Cache pages so that the database doesn't get hit as often. This is useful especially with many users hitting the index page. 
Also create the `get_page` function so that we don't inadvertently cache some user data. Only cache the actual page in the database.

Cache pages

---

CTFd/config.py
CTFd/utils.py

Update `get_config` to check both upper & lower case, add more caching documentation, simplify example REDIS URL, and let us specify the REDIS_URL automatically.
Closes #354

Improve caching and config

---

CTFd/challenges.py
CTFd/utils.py
tests/helpers.py
tests/user/test_challenges.py

Provides functions to cast into unicode in Python 2. I think the underlying SQLite DBAPI is confused about how to deal with the unicode. Also tested this with MySQL.
Closes #377

Fixing unlocking hints for challenges with unicode names

---

CTFd/themes/original/static/js/chalboard.js

Occasionally the amount of solves shown ("17 Solves") and the amount of solves shown in the modal can differ due to the time the values are gotten. Instead, always update the value shown so that people don't get scared that CTFd might be broken.
Closes #402

Update the amount of solves shown on the chal window when solves are listed

---

.gitignore
CTFd/plugins/__init__.py
tests/test_plugin_utils.py

This adds plugin wrappers for: 
```
override_template
register_plugin_script
register_plugin_stylesheet
```
They weren't outright moved because of a circular import. Regardless it *seems* simpler to simply call them within the context of the app. We also avoid breaking any existing plugins. 
Closes #398

Add plugin wrappers for plugin related utils functions

---

CTFd/admin/challenges.py
CTFd/models.py
CTFd/plugins/challenges/__init__.py
CTFd/plugins/challenges/assets/standard-challenge-update.js
CTFd/themes/admin/static/js/chalboard.js
tests/admin/test_admin_facing.py

This allows challenge types to have custom tables. In addition, the challenge type plugins now have a static interface which needs to be implemented by every challenge type plugin. 
This allows people to create, read, update, and delete custom challenge types.

Custom challenge tables

---

CTFd/challenges.py
tests/helpers.py
tests/user/test_challenges.py

Preventing Hints from being unlocked after the end of a CTF unless challenges can be viewed in which case they are available for purchase after the CTF. 
Hints are purchaseable during the CTF and when a CTF is frozen.

Preventing Hints from being unlocked after the end of a CTF 

---

CTFd/challenges.py
tests/user/test_auth.py
tests/user/test_user_facing.py

Clean up the verify_emails logic a little. Test the behavior for viewing challenges while unregistered and requiring verified emails. 
Also ensuring that if both are set, users should be able to see challenges but be prevented from seeing them until they confirm their email address.

Adding tests for verify_emails and user_can_view_challenges are set

---

CTFd/admin/teams.py
CTFd/themes/admin/templates/teams.html
tests/admin/test_admin_facing.py

Closes #469
- Adds a "New Team" button to the admin "Teams" page
- Reuses the update team modal for for creating new teams
- Adds an API route to allow admins to create a new team
- Adds unit tests to cover added python code

Admin Team List - New Team

---

CTFd/admin/teams.py
CTFd/auth.py
CTFd/themes/original/templates/login.html
CTFd/themes/original/templates/reset_password.html
CTFd/utils.py
CTFd/views.py
tests/test_utils.py
tests/user/test_user_facing.py

Closes #34 by reducing some auth restrictions:
* Team names cannot be email addresses. 
* Teams can login with team names or email address now
* Password reset isn't shown to the user if the server isn't configured to send mail. 
* `utils.check_email_format()` now exists to check email format

34 reduce auth restrictions

---

CTFd/utils.py
tests/user/test_user_facing.py

Closes #472 
Add an `authed_only` decorator. Doesn't seem worth it to change much of the existing logic yet but plugins can make use of it.

Authed only

---

CTFd/__init__.py

Fix database migrations so that we don't stamp before we upgrade. 
Only stamp if we run into a situation where CTFd is upgrading from before there were migrations.

Fix migration upgrades

---

CTFd/utils.py
tests/test_utils.py

Closes #498 by checking for multiple date formats
Resolves some import conflicts with IDs not matching up and conflicts with users having the same team name. 
All exports should include their alembic_version or else we're just guessing when the export came from.

Improve imports/exports to reduce the likelihood of a conflict

---

CTFd/auth.py
CTFd/themes/core/templates/confirm.html
CTFd/utils.py
tests/user/test_auth.py
tests/user/test_user_facing.py

Adds some better messaging for invalid confirmation & email links. 
Also adds tests for invalid tokens.

Adding an error message for invalid confirm/reset links 

---

CTFd/admin/statistics.py
CTFd/utils.py

Update checks only happen every 12 hours now and the check function is called when you load the admin/statistics page.

Delay update check by 12 hours each call and call update check in admin panel

---

CTFd/__init__.py

This properly overrides the jinja_environment because blueprints need a slightly modified Jinja environment. 
https://github.com/pallets/flask/blob/a43a439c7a839edc8c5ac7062acb694eceb99e55/flask/templating.py#L33

Properly override the jinja environment

---

CHANGELOG.md
CTFd/__init__.py

Some people were annoyed last time there was an upgrade with the upgrade confirmation requiring using debug mode. 
I think I share that annoyance so it only applies if there's a TTY to use now. 
Also marking 1.1.0 in __version___

Only prompt for upgrades if there's a TTY & mark 1.1.0

---

CHANGELOG.md
CTFd/__init__.py

Marks the 1.1.1 release which fixes a few issues in 1.1.0. 
**General**
* Fixed regression where users could not be promoted to admins or verified.
* Fixed two icons in the Media Library which were not updated to Font Awesome 5.
* Challenge previews now include tags, hints, and files. 
* Fixed an issue where a page could not be published immediately after being saved.
**Themes**
* Upgraded to Bootstrap 4 Beta v3. No major changes needed by themes. 
* Fixed issue where the frozen message was not centered in the team page.
* The JavaScript `update()` function now has a callback instead of being hardcoded.
* `chalboard.js` now passes `script_root` into the Nunjucks templates so that file downloads work properly under subdirectories.

Mark 1.1.1

---

CTFd/plugins/__init__.py
CTFd/utils.py
tests/test_plugin_utils.py

Add a bypass_csrf_protection decorator to allow routes to forego CSRF nonce protection on POST requests.

Bypass csrf plugins

---

import.py

The check for the second argument is mistaken and causes an exception instead of the intended behavior. This PR fixes that.
```
python import.py backup.zip 
* Loaded module, <module 'CTFd.plugins.challenges' from '/opt/CTFd/CTFd/plugins/challenges/__init__.pyc'>
* Loaded module, <module 'CTFd.plugins.keys' from '/opt/CTFd/CTFd/plugins/keys/__init__.pyc'>
Traceback (most recent call last):
File "import.py", line 11, in <module>
if sys.argv[2]:
IndexError: list index out of range
```

import.py: Proper check for second argument

---

CTFd/challenges.py
tests/user/test_challenges.py

Noticed that users explicitly hidden from the scoreboard could not see their own solves. 
The solves endpoint should only ever give you your own solves.

Fix banned users not being able to see their own solves

---

Dockerfile

Separately add `requirements.txt`, then run `pip install`, then add remaining files so as to not cause re-installation of python packages whenever any code files change. Should help make for faster docker-based dev cycle.

reorganized Dockerfile to improve layer caching

---

CTFd/challenges.py

We had to hot-patch this after we saw users exploiting it, submitting correct flags for challenges that weren't even released yet.

Fix access to unreleased challenges through /chals/<id> endpoint

---

CTFd/admin/__init__.py

- Wraps exceptions on `/admin/import` returned to users in a `repr()`, making debugging easier.

Display import_ctf Exceptions via repr

---

CTFd/config.py
docker-entrypoint.sh

This allows to set `APPLICATION_ROOT` externally by setting an env variable, making hosting under a subfolder easier. The `dockerfile-entrypoint.sh` has been adapted accordingly, so the `APPLICATION_ROOT` env var can be passed when calling `docker` or set in the `docker-compose.yml` file.

setting APPLICATION_ROOT from env var

---

.codecov.yml
CTFd/schemas/users.py
tests/api/v1/test_users.py

The Edit User page has a form field to modify the user's Verified, Hidden and Banned status. Both the Hidden and Banned status can be modified by an admin, however the Verified status cannot be modified. This appears to be a bug.
There are two potential solutions for this bug:
- Remove the Verified field from the form
- Allow admin to modify `verified` field in `UserSchema`
In this pull request I propose that admins should be allowed access to modify the `verified` field in `UserSchema`. 
This change has two advantages:
- It makes the existing Edit User form work as intended. 
- It allows admins to manually verify users, which enables contests to employ user verification without setting up a mail server.

Fix admin cannot modify verified status in Edit User

---

CTFd/config.py
CTFd/themes/admin/static/js/configs/configs.js
CTFd/themes/admin/templates/configs/email.html
CTFd/utils/email/smtp.py
tests/users/test_auth.py
tests/utils/test_email.py

* Closes #779
* This brings back MAIL_USEAUTH and allows you to set it from `config.py`
* Prevent saving configs from overwriting saved SMTP username and password

Fix smtp sendmail 

---

.travis.yml
CTFd/utils/uploads/uploaders.py
development.txt
tests/utils/test_uploaders.py

* Empty S3 buckets can not return Contents so we need to check for that.

Fix syncing down an empty S3 bucket

---

CTFd/api/v1/hints.py
CTFd/themes/admin/static/js/challenges/hints.js
CTFd/themes/admin/templates/challenges/challenge.html
tests/api/v1/test_hints.py

* Fix hint loading for admins by adding /api/v1/hints/<id>?preview=true for use by admins
* Add tests for admin Hint preview
* This also starts integrating the core and admin themes meaning that the core theme cannot be removed from CTFd and is available for usage by other themes

Fix hint loading for admins with /api/v1/hints/<id>?preview=true

---

CTFd/__init__.py

* Disable jinja cache properly by setting cache_size to 0 (#662)
* Without disabling the cache you get some difficult to debug rendering errors. Regression from 1.2.0.

Disable jinja cache properly by setting cache_size to 0 (#662)

---

CTFd/plugins/dynamic_challenges/__init__.py
tests/challenges/test_dynamic.py

I noticed that when I wanted to add a pre-requisite challenge to a dynamic challenge, I received a divison-by-zero error.
During a requirement addition, only the new required challenge id is sent. Because the initial, minimum and decay values are not set, the update path in the __init.py set them to a default 0. 
Later on, when a calculation takes place with these values, a divison-by-zero happens before anything gets committed to the database.
I've added a simple check before other calculations to check if data received from client includes a requirements (is not None). If there is data there, it means the request is a requirement addition so we can just commit those changes and return. At the same time, updating values and other data will not include a requirement field so everything …

Fix divison-by-zero when adding requirement to dynamic challenge

---

CHANGELOG.md
CTFd/__init__.py

2.0.1 is a patch release to fix regressions and bugs in 2.0.0. 
If you are upgrading from a version prior to 2.0.0 please read the 2.0.0 change notes for instructions on updating to 2.0.0 before updating to 2.0.1. 
**General**
* Fix setting auth for `get_smtp()`. 
* Add `MAIL_USEAUTH` to `config.py`.
* Add more mail documentation to `config.py`.
* Disable jinja cache properly by setting `cache_size` to 0 (#662)
Regression from 1.2.0.
* Fix downloading files as an anonymous user. 
* Fix viewing challenges anonymously if they have empty requirements. Closes #789
* Allow anonymous users to see see challenges with empty requirements or anonymized challenges
* Clean up admin mail settings to use new label/small structure
* Fix email confirmations and improve test.
* Fix password resets from …

Mark 2.0.1 release

---

CTFd/themes/admin/templates/configs/appearance.html

* Disable user mode switching on client side (Closes #799)
It's ill advised to switch user modes after a CTF is setup. The simplest thing to do here is to require CTF resetting in order to switch modes. If it makes sense this can be re-enabled and re-evaluated.

Disable user mode switching on client side (Closes #799)

---

.travis.yml
CTFd/__init__.py
CTFd/utils/decorators/__init__.py
CTFd/utils/decorators/visibility.py
CTFd/utils/initialization/__init__.py
CTFd/views.py
tests/helpers.py
tests/test_themes.py
tests/users/test_auth.py
tests/users/test_views.py

* Fix subdirectory deployments in a generic manner by modifying`request.path` to combine both `request.script_root` and `request.path` and also creating a request preprocessor to redirect users into the true CTFd app. Without this sessions will be invalid because sessions will be set to a subdirectory. 
* Add a test for testing subdirectory deployments and the customized CTFdRequest object.
* Fix `TestingConfig.SAFE_MODE` getting stuck in between tests. 
* Order AWS keys properly in travis.yml
* Redirect to `request.full_path` instead of just `request.path`

Fix subdirectory deployments in a generic manner

---

CHANGELOG.md
CTFd/__init__.py

2.0.2 / 2019-01-03
**General**
* Fix regression where public challenges could not be attempted by unauthed users.
* Admin Config Panel UI no longer allows changing of user mode.
* Show notification titles and allow for deleting notifications
* Update notification UI in admin panel to be similar to the public-facing UI
* Fix subdirectory deployments in a generic manner by modifying `request.path` to combine both `request.script_root` and `request.path`.
* Also create a request preprocessor to redirect users into the true CTFd app when deploying on a subdirectory.
* Redirect to `request.full_path` instead of just `request.path`.
* Fix `TestingConfig.SAFE_MODE` not being reset between tests.
* Disable `value` input in dynamic challenge update field since we calculate it on …

Mark 2.0.2

---

CTFd/plugins/challenges/assets/view.js
CTFd/plugins/dynamic_challenges/assets/view.js
CTFd/themes/admin/static/js/challenges/challenge.js
CTFd/themes/admin/static/js/challenges/files.js
CTFd/themes/admin/static/js/challenges/flags.js
CTFd/themes/admin/static/js/challenges/hints.js
CTFd/themes/admin/static/js/challenges/new.js
CTFd/themes/admin/static/js/challenges/requirements.js
CTFd/themes/admin/static/js/challenges/tags.js
CTFd/themes/admin/static/js/configs/configs.js
CTFd/themes/admin/static/js/notifications/notifications.js
CTFd/themes/admin/static/js/pages/editor.js
CTFd/themes/admin/static/js/pages/media.js
CTFd/themes/admin/static/js/pages/pages.js
CTFd/themes/admin/static/js/scoreboard/scoreboard.js
CTFd/themes/admin/static/js/submissions/submissions.js
CTFd/themes/admin/static/js/teams/actions.js
CTFd/themes/admin/static/js/teams/info.js
CTFd/themes/admin/static/js/teams/new.js
CTFd/themes/admin/static/js/users/actions.js
CTFd/themes/admin/static/js/users/info.js
CTFd/themes/admin/static/js/users/new.js
CTFd/themes/core/static/js/CTFd.js
CTFd/themes/core/static/js/hints.js
CTFd/themes/core/static/js/settings.js
CTFd/utils/initialization/__init__.py
tests/api/v1/test_csrf.py
tests/helpers.py

* Require CSRF-Token header on state changing API requests
* Require CSRF nonces on more than just POSTs, 
* Replace usage of `fetch()` with custom `CTFd.fetch()` implementation

Require CSRF-Token header on state changing API requests

---

CHANGELOG.md
CTFd/__init__.py

2.0.3 / 2019-01-12
**Security Release**
This release resolves a security issue that allowed malicious users to hijack admin browser sessions in certain browsers under certain configurations.
Because of the necessary changes to the API, the previously used call to `fetch()` in themes should now be replaced with `CTFd.fetch()`.
**Security**
* Require `CSRF-Token` header on all API requests.
* Require CSRF protection on all HTTP methods except `GET`, `HEAD`, `OPTIONS`, and `TRACE`.
* Default session cookie to `SameSite=Lax`
* Send initial user information request to MajorLeagueCyber over HTTPS
**Themes**
* Remove explicit usage of script_root in public JS. 
* Instead use the `CTFd.fetch()` function (defined in `CTFd.js`) and properly register the url root and CSRF nonce in …

Mark 2.0.3

---

CTFd/auth.py
CTFd/cache/__init__.py
CTFd/schemas/teams.py
CTFd/schemas/users.py
CTFd/utils/__init__.py
CTFd/utils/email/__init__.py
tests/api/v1/test_users.py

* Block user name changes if name changes are disabled (Closes #835 )
* Block team name changes  if name changes are disabled
* Set accounts to unconfirmed if email is changed while `verify_emails` is enabled
* Only allow users to change their email to emails with domains in the whitelist. 
* Add `email.check_email_is_whitelisted()` to verify that a user's email is whitelisted.
* Create a get_config wrapper around the internal _get_config to let us set a default config value (Closes #659)
* Remove `utils.get_app_config()` from memoization and also give it a `default` parameter

Consider account configs when user patches their own account

---

CTFd/auth.py
tests/helpers.py
tests/oauth/test_redirect.py

* Block the creation of users/teams from MLC if `registration_visibility` is private
* Add OAuth flow tests

Block new user registration if registering via MLC

---

docker-compose.yml
docker-entrypoint.sh

* Stop gunicorn from logging to `LOG_FOLDER` in docker without explicit opt-in
* Re-add the `LOG_FOLDER` envvar to docker-compose so we don't try to write to the read-only host
* Add `ACCESS_LOG` and `ERROR_LOG` envvars to docker to specify where gunicorn will log to

Revert 762 log envvar

---

docker-compose.yml
docker-entrypoint.sh

* Closes #846 
* Allow DATABASE_URL to contain custom MySQL ports for docker-entrypoint.sh
* Drop WORKERS count to 1 to avoid dealing with Flask-SocketIO sticky sessions'

Allow custom MySQL ports in docker entrypoint

---

.travis.yml
CTFd/__init__.py
CTFd/api/v1/notifications.py
CTFd/config.py
CTFd/events/__init__.py
CTFd/themes/core/static/js/events.js
CTFd/utils/events/__init__.py
CTFd/utils/initialization/__init__.py
requirements.txt
serve.py
tests/helpers.py
tests/utils/test_events.py

* Remove Flask-SocketIO in favor of custom Server Side Events code (#852)
* Remove `SOCKETIO_ASYNC_MODE` config
* Allow `create_ctfd()` test helper to take app configuration as an argument

Remove Flask-SocketIO in favor of custom Server Side Events code (#852)

---

CHANGELOG.md
CTFd/__init__.py

2.0.4 / 2019-01-30
**General**
* Block user & team name changes if name changes are disabled (Closes #835)
* Set accounts to unconfirmed if email is changed while `verify_emails` is enabled
* Only allow users to change their email to emails with domains in the whitelist.
* Add `email.check_email_is_whitelisted()` to verify that a user's email is whitelisted.
* Create a `get_config` wrapper around the internal `_get_config` to let us set a default config value (Closes #659)
* Remove `utils.get_app_config()` from memoization and also give it a `default` parameter
* Move `utils.logging.init_logs()` into `utils.initialization` and properly call `init_logs()` to save logs to the logs folder
* Block the creation of users/teams from MLC if registration_visibility is private
* …

Mark 2.0.4

---

CTFd/themes/admin/static/css/base.css
CTFd/themes/admin/templates/modals/challenges/flags.html
CTFd/themes/admin/templates/modals/challenges/hints.html

* Closes #876
* Fixes overflowing admin panel content by adding the `.text-break` CSS class.
* This is .text-break cloned from Bootstrap 4.3 with a fix for browsers not supporting break-word. It will be removed from the main CTFd classes when Bootstrap is upgraded internally.

Fix for overflowing content preventing edit and deletion in admin panel

---

CTFd/auth.py

It looks like this log output was copied and pasted from the reset password route. Also, the `{name}` format specifier resolves to `None` in cases where the user is not logged in (`session.get('name')` is None), but confirms the CTFd email.
Before:
```
[03/16/2019 18:59:30] x.x.x.x -  successful password reset for None
```
After:
```
[03/16/2019 19:10:39] x.x.x.x - successful confirmation for Test Team
```

Fix email confirmation log line

---

CTFd/utils/email/smtp.py
tests/utils/test_email.py

The CTFd/utils/email/smtp.py file has a provision to read SMTP
configuration for all fields from either the UI or CTFd/config.py file.
Two fields, `MAIL_SERVER` and `MAIL_PORT`, were not being read from the
config.py file. This commit fixes this issue.

Read smtp server configuration from config.py

---

CTFd/api/v1/teams.py
CTFd/api/v1/users.py
CTFd/teams.py
CTFd/users.py
tests/api/v1/test_teams.py
tests/api/v1/test_users.py
tests/teams/test_teams.py
tests/users/test_submissions.py
tests/users/test_users.py

* Properly hide users/teams if they are set to hidden/banned
* This should be in the API and in the main user panel. This should not affect admins. 
* Update tests to reflect this behavior.

Properly hide users/teams if they are set to banned/hidden

---

CHANGELOG.md
CTFd/__init__.py

2.0.6 / 2019-04-08
**Security**
* Fixes an issue where user email addresses could be disclosed to non-admins
**General**
* Users/Teams set to hidden or banned are no longer visible by other users
* This affects the API and the main user interface. This does not affect admins.
* Users without Teams can no longer view challenges when the CTF is in Team Mode

Mark 2.0.6

---

CTFd/api/v1/scoreboard.py
CTFd/api/v1/submissions.py
CTFd/cache/__init__.py
tests/api/v1/test_scoreboard.py

* Cache `/api/v1/scoreboard` and `/api/v1/scoreboard/top/[count]`
* Adds `cache.make_cache_key` because Flask-Caching is unable to cleanly determine the endpoint for Flask-Restful/Restplus
* This helper may change in a future release or be deprecated by an improvement in Flask-Caching.
* Closes #874

Add cache.make_key_prefix to allow us to cache and invalidate API responses

---

.travis.yml
Makefile
development.txt
tests/helpers.py
tests/users/test_views.py

* Make tests run in parallel with `pytest-xdist`
* When using a non-memory database, test helpers will now randomize the database so that tests can run in parallel
* Upgrade to `pytest` 4.4.0

Speed up testing with parallelization 

---

CTFd/api/v1/users.py
CTFd/config.py
CTFd/themes/admin/static/js/users/new.js
CTFd/themes/admin/templates/modals/users/edit.html
CTFd/themes/admin/templates/users/user.html
CTFd/utils/email/__init__.py

* Add `/api/v1/users?notify=true` to email user & password after creating new account. 
* Separate `admin/templates/modals/users/create.html` into `admin/templates/modals/users/edit.html`
* Return result of email wrapper functions in `CTFd.utils.email`
* SWAGGER_UI config.py setting to properly default to `/`

Add ability to send user email for created account notification

---

CTFd/utils/initialization/__init__.py
Dockerfile

* Catch IOError issues (i.e. permission issues) with writing to log files
* Related to #844
* Logs now have a sys.stdout handler
* Update Dockerfile to create and chown/chmod the folders used by `docker-compose` to store files/logs (`/var/log/CTFd`, `/var/uploads`)
* Closes #961

Fix logging without root in container

---

CHANGELOG.md
CTFd/__init__.py

2.1.0 / 2019-04-24
**General**
* Remove Flask-SocketIO in favor of custom Server Side Events code
* Removed the Flask-SocketIO dependency and removed all related code. See **Deployment** section.
* Added EventSource polyfill from Yaffle/EventSource
* Events are now rate-limited and only availble to authenticated users
* This means real time notifications will only appear to authenticated users
* Browser localStorage is now used to dictate which tab will maintain the persistent connection to the `/events` endpoint
* Thanks to https://gist.github.com/neilj/4146038
* Notifications (currently the only use of the events code) now appear with a notification sound
* Thanks to [Terrence Martin](https://soundcloud.com/tj-martin-composer) for the sound
* Added UI to delete and …

Mark 2.1.0 and update CHANGELOG

---

CHANGELOG.md
README.md
docker-compose.yml
docker-entrypoint.sh

Drop the default worker count in `docker-entrypoint.sh` because the default memory usage was higher than it needed to be. If you need more workers you can still increase the values and set a `SECRET_KEY` as before.

Reduce default gunicorn worker count to reduce memory usage

---

CTFd/utils/exports/__init__.py
Makefile
requirements.txt
tests/utils/test_exports.py

* Fix imports/exports to accept JSON 
* MariaDB does not properly understand JSON so it must accept strings instead of dicts
* MariaDB outputs strings instead of JSON for its JSON type so the export serializer will attempt to cast output JSON strings to JSON objects
* Update Makefile to not lint any uploads
* Update Flask-SQLAlchemy to 2.4.0 to remove a large amount of warnings

Fix imports/exports and update Flask-SQLAlchemy to reduce warnings

---

CTFd/api/v1/challenges.py
tests/api/v1/test_challenges.py

* Allow admins to hit `/api/v1/challenges` and `/api/v1/challenges/[id]` without having a team

Fix challenge preview for admins

---

CTFd/api/v1/challenges.py
tests/api/v1/test_challenges.py

Resolves #975. See that issue for the problem details.
I just corrected the parameter of `get_wrong_submissions_per_minute` from `session['id']` to `user.account_id`. Also, I added test cases for rate-limiting of flag submission and team mode.

 Fix rate-limiting of flag submission when using team mode

---

CTFd/models/__init__.py
migrations/versions/b295b033364d_add_ondelete_cascade_to_foreign_keys.py
populate.py
tests/admin/test_config.py
tests/api/v1/teams/test_team_members.py
tests/api/v1/test_challenges.py
tests/api/v1/test_teams.py
tests/api/v1/test_users.py
tests/helpers.py

* Fixes `populate.py` to assign captains to teams.
* Adds `ondelete='CASCADE'` to most ForeignKeys in models
* Closes #794 
* Test reset in team mode to test removing teams with captains
* Test deleting users/teams with awards to test cascading deletion
* `gen_team()` test helper now creates users for the team and assigns the first one as captain
* Added `Challenges.flags` relationship and moved the `Flags.challenge` relationship to a backref on `Challenges`

Adds ondelete='CASCADE' to some models. 

---

docker-compose.yml

* Docker Compose needs to be run as root to be able to write to the bind mounted volumes.

Run as root when using docker-compose to be able to write to the volume

---

CHANGELOG.md
CTFd/__init__.py

2.1.1 / 2019-05-04
**General**
* Allow admins to hit `/api/v1/challenges` and `/api/v1/challenges/[id]` without having a team to fix challenge previews
* Fix rate-limiting of flag submission when using team mode
* Fixes some modal close buttons not working in the admin panel
* Fixes `populate.py` to assign captains to teams.
**Models**
* Added `Challenges.flags` relationship and moved the `Flags.challenge` relationship to a backref on Challenges
* Added `ondelete='CASCADE'` to most ForeignKeys in models allowing for deletions to remove associated data
* `Hints` should be deleted when their Challenge is deleted
* `Tags` should be deleted when their Challenge is deleted
* `Flags` should be deleted when their Challenge is deleted
* `ChallengeFiles` should be deleted when …

Mark 2.1.1

---

.gitignore
CTFd/api/v1/challenges.py
CTFd/api/v1/teams.py
CTFd/api/v1/users.py
CTFd/models/__init__.py
tests/api/v1/test_challenges.py
tests/api/v1/test_teams.py
tests/api/v1/test_users.py

* Fix freeze time regressions in 2.x
* Make `/api/v1/[users,teams]/[me,id]/[solves,fails,awards]` endpoints load as admin to load all rows and bypass freeze
* Closes #988
* Make `/api/v1/challenges/[id]/solves` respect freeze time. `/api/v1/challenges/[id]/solves?preview=true` is exposed for admins to see solves as a user would. 
* Closes #986

Fix freeze time regressions

---

CHANGELOG.md
CTFd/__init__.py

2.1.2 / 2019-05-13
**General**
* Fix freeze time regressions in 2.x
* Make `/api/v1/[users,teams]/[me]/[solves,fails,awards]` endpoints load as admin so users can see their solves after freeze
* Make `/api/v1/challenges/[id]/solves` only show solves before freeze time
* Add the `?preview=true` GET parameter for admins to preview challenges solves as a user
* Team join attempts are now ratelimited
**Tests**
* More linting and autoformatting rules
* Format Javascript and CSS files with `prettier`: `prettier --write 'CTFd/themes/**/*'`
* Format Python with `black`: `black CTFd` and `black tests`
* `make lint` and thus Travis now include the above commands as lint checks
* Travis now uses xenial instead of trusty.

Mark 2.1.2

---

docker-entrypoint.sh

* Use `/dev/shm` for `--worker-tmp-dir` in gunicorn in Docker

Use /dev/shm for worker-tmp-dir in gunicorn in Docker

---

CTFd/auth.py

* Properly redirect to `teams.private` instead of `teams.new`

Properly redirect to teams.private instead of teams.new

---

CTFd/utils/config/pages.py
tests/test_views.py

* Fixes bug where pages marked as `hidden` weren't loading
* It's possible that some users used this behavior however this fix implements the correct behavior. The `draft` setting can be used to completely hide pages.

Fix hidden pages not being able to load

---

CTFd/themes/admin/templates/pages.html

* Remove `data-href` from `pages.html` to fix the delete button
* The delete action propagates too much causing issues. This should be re-implemented on page editor rewrite.

Remove data-href from pages.html to fix delete button

---

CTFd/api/v1/teams.py
CTFd/api/v1/unlocks.py
CTFd/api/v1/users.py
CTFd/cache/__init__.py
CTFd/models/__init__.py
CTFd/utils/__init__.py
CTFd/utils/config/pages.py
CTFd/utils/scores/__init__.py
development.txt
requirements.txt
serve.py
tests/api/v1/test_teams.py
tests/api/v1/test_users.py
tests/helpers.py

* Cache get place code for users and teams. 
* Fix score changing test helpers to clear standings cache when generating a score changing row
* `utils._get_config` will now return `KeyError` instead of None. 
* Separate `/api/v1/[users,teams]/[me,id]/[solves,fails,awards]` into seperate API endpoints
* Install `Flask-DebugToolbar` in development
Main goals covered in #1012

Improve caching 

---

CTFd/cache/__init__.py
CTFd/scoreboard.py
tests/api/v1/test_scoreboard.py

* Cache the `/scoreboard` page to avoid having to rebuild the response so often
* Update `tests.api.v1.test_scoreboard:test_scoreboard_is_cached` to also test if `/scoreboard` is cached

Cache scoreboard page

---

CTFd/__init__.py
CTFd/utils/exports/__init__.py
CTFd/utils/migrations/__init__.py

stamp() call missing the migrations directory causes apache2 w/ mod_wsgi support to break.
Issues #257 seems to be directly related to this issue, but was never fixed because the user moved onto another deployment method.

Fixed bug that caused apache2+wsgi deployment to break

---

CTFd/utils/exports/__init__.py
tests/utils/test_exports.py

* Temporarily disable foreign keys in MySQL, MariaDB, and Postgres during `import_ctf()`
* Likely also disables SQLite but SQLite is permissive about foreign keys to begin with so irrelevant.

Disable foreign keys during import

---

CTFd/admin/__init__.py

* Add `cache_timeout` parameter to `send_file`response in `/admin/export`.
* Closes #1032

Prevent browser from caching the export

---

CTFd/api/v1/challenges.py
CTFd/api/v1/scoreboard.py
CTFd/themes/core/static/js/scoreboard.js

* Fixes account links on the scoreboard page created by `update()`. They now correctly point to the user instead of undefined when in user mode. 
* Add `account_type` and `account_url` field in `/api/v1/scoreboard`

Fix scoreboard links created by update() in user mode

---

CHANGELOG.md
CTFd/__init__.py

2.1.3 / 2019-06-22
**General**
* Fix issue with downloading files after CTF end when `view_after_ctf` is enabled
* Sort solves in admin challenge view by date
* Link to appropriate user and challenge in team, user, and challenge pages
* Redirect to `/team` instead of `/challenges` after a user registers in team mode
* Fixes bug where pages marked as `hidden` weren't loading
* Remove `data-href` from `pages.html` in the Admin Panel to fix the delete button
* Add UI to handle team member removal in Admin Panel
* Fixes account links on the scoreboard page created by `update()`. They now correctly point to the user instead of undefined when in user mode.
* `utils._get_config` will now return `KeyError` instead of `None` to avoid cache misses
**Deployment**
* Use `/dev/shm` …

Mark 2.1.3

---

CTFd/utils/uploads/uploaders.py

* Add a Content-Disposition header to s3 downloads so `wget` doesn't generate long invalid filenames.

Add a Content-Disposition header to s3 downloads

---

docs/plugins.rst

I was going through the plugin documentation and noticed a minor error. 
This PR fixes the description for the link to plugins repo

Fixed minor error in plugin doc

---

Dockerfile

Revert "Switch Dockerfile from python:2.7-alpine to python:3.7-alpine
This reverts commit 7eff04dc4c26234f4c062222e7eb9ef87b722623.
Better to put this into 2.2.0 even though I suspect there's no major breaking changes here.

Revert "Switch Dockerfile from python:2.7-alpine to python:3.7-alpine

---

CTFd/utils/uploads/uploaders.py

* Fixes a bug in S3 downloads where a downloaded file would have its parent folder name in the filename

Fix S3 file downloads to not contain the folder name

---

CTFd/api/v1/challenges.py
CTFd/api/v1/teams.py
CTFd/utils/decorators/__init__.py
tests/api/v1/teams/test_team_members.py
tests/api/v1/test_teams.py

* Add require_team decorator to endpoints that request teams.
* Change status code for captain endpoints to return 403 instead of 400

Fix missing Team API exceptions

---

CTFd/admin/__init__.py
tests/admin/test_export_csv.py

* Fix CSV exports in Python 3
* Related: https://github.com/pallets/flask/issues/3358

Fix CSV exports in Python 3 by converting StringIO to BytesIO

---

CTFd/schemas/teams.py
CTFd/schemas/users.py
tests/api/v1/test_teams.py
tests/api/v1/test_users.py

* Prevent users from nulling out profile values

Prevent users from nulling out profile values

---

CTFd/api/v1/challenges.py

I use a SIEM to collect CTFd logs and i want to make the top 10 challenges with the most incorrect submissions.
Adding the challenge identifier to submission logs will allow to get the challenge linked to the submission.

Add challenge id in flag submission log

---

CHANGELOG.md
CTFd/__init__.py
docs/conf.py

2.1.5 / 2019-10-2
=================
**General**
* Fixes `flask run` debug server by not monkey patching in `wsgi.py`
* Fix CSV exports in Python 3 by converting StringIO to BytesIO
* Avoid exception on sessions without a valid user and force logout
* Fix several issues in Vagrant provisioning
**API**
* Prevent users from nulling out profile values and breaking certain pages

Mark 2.1.5

---

CTFd/utils/decorators/__init__.py

* Detect `text/event-stream` in `authed_only` to prevent unnecessary redirects to `/login`

Don't redirect the /events endpoint to login

---

CTFd/themes/core/templates/base.html

* Add icons to user-side navbar options
* Ambiguous "Admin" link renamed to "Admin Panel"
* Closes #1104, #1113

Add icons to user-side navbar options

---

CTFd/themes/core/templates/notifications.html

Just a cosmetic fix so there isn't a blank page staring at you.

Add note to notifications template when none exist

---

CTFd/__init__.py
CTFd/utils/helpers/__init__.py
CTFd/utils/initialization/__init__.py

* Closes #912 
* Adds the `d` parameter to urls generated for static assets to bust the browser cache

Use generally unique string to bust browser cache on server restart

---

CTFd/utils/exports/__init__.py

* Rearrange `import_ctf()` code to block invalid and outdated backups 
* Closes #1157

Prevent old CTFd backups from going through import process

---

CTFd/utils/email/__init__.py
CTFd/utils/validators/__init__.py
tests/utils/test_email.py
tests/utils/test_validators.py

* Close #1184 and properly close #622 by using the correct relaxed email regex
* Deprecate `CTFd.utils.email.check_email_format()`

Properly use relaxed email regex (Closes #1184)

---

migrations/1_2_0_upgrade_2_0_0.py

[flake8](http://flake8.pycqa.org) testing of https://github.com/CTFd/CTFd on Python 3.8.0
$ __flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics__
```
./migrations/1_2_0_upgrade_2_0_0.py:24:38: F821 undefined name 'six'
elif value and isinstance(value, six.string_types):
^
1     F821 undefined name 'six'
1
```
https://flake8.pycqa.org/en/latest/user/error-codes.html
* F82 tests are almost always _undefined names_ which are usually a sign of a typo, missing imports, or code that has not been ported to Python 3.  These also would be compile-time errors in a compiled language but in Python a __NameError__ is raised which will halt/crash the script on the user.

undefined name 'six' in 1_2_0_upgrade_2_0_0.py

---

README.md

* Replace references to the CTFd Slack with MLC Discourse references

Remove CTFd Slack references in README to reference MLC Discourse

---

CHANGELOG.md
CTFd/__init__.py
docs/conf.py
package.json

2.2.2 / 2020-01-09
**General**
* Add jQuery, Moment, nunjucks, and Howl to window globals to make it easier for plugins to access JS modules
* Fix issue with timezone loading in config page which was preventing display of CTF times

Mark 2.2.2

---

CTFd/auth.py
CTFd/schemas/teams.py
CTFd/schemas/users.py
CTFd/teams.py
CTFd/utils/email/__init__.py
tests/users/test_auth.py
tests/utils/test_email.py

* Usernames are now properly stripped before being used in registration checks
* Reset password function now uses email addresses instead of user names for tokens
* Prevent MLC users from resetting their password

Strip spaces on registration and refine password reset

---

CTFd/utils/security/signing.py
CTFd/utils/sessions/__init__.py

* Sign sessions using `SECRET_KEY`
* Add `CTFd.utils.security.signing.sign` and `CTFd.utils.security.signing.unsign`

Sign sessions using SECRET_KEY to simplify revocation

---

CHANGELOG.md
CTFd/__init__.py
docs/conf.py
package.json

2.2.3 / 2020-01-21
All CTFd administrators are recommended to take the following steps:
1. Upgrade their installations to the latest version
2. Rotate the `SECRET_KEY` value
3. Reset the passwords for all administrator users
**Security**
* This release includes a fix for a vulnerability allowing an arbitrary user to take over other accounts given their username and a CTFd instance with emails enabled
**General**
* Users will receive an email notification when their passwords are reset
* Fixed an error when users provided incorrect team join information

Mark 2.2.3

---

CTFd/utils/email/mailgun.py
CTFd/utils/email/smtp.py
tests/users/test_auth.py
tests/utils/test_email.py

* Fix SMTP email From header to display human readable name
* Remove "Admin" from the From header in the Mailgun integration

Fix SMTP email From header and remove 'Admin' from the From header

---

manage.py

* Adds `get_config` and `set_config` commands to `manage.py` to manipulate the Config table from a CLI
* Closes #1226

Add config manipulation to manage.py

---

Makefile
development.txt

* Add `make coverage` to generate an HTML coverage report
* Update `coverage` and `pytest-cov` development dependencies

Generate a better coverage report with 'who tests what' context

---

CHANGELOG.md
CTFd/__init__.py
docs/conf.py
package.json

2.3.2 / 2020-03-15
**General**
* Fix awards not being properly assigned to teams in `TEAMS_MODE`
**API**
* Set `/api/v1/statistics/users` route to be admins_only
* When POST'ing to `/api/v1/awards`, CTFd will look up a user's team ID if `team_id` is not specified
* Adds a setting to registration visibility to allow for MLC registration while registration is disabled
* Fix setting theme color during the setup flow and from the Admin Panel
**Themes**
* Fixes users/admins being able to remove profile settings.
* Previously a bug prevented users from removing some profile settings. Now the `core` theme stores the initial value of inputs as a `data` attribute and checks for changes when updating data. This should be a temporary hack until a proper front-end …

Mark 2.3.2

---

CTFd/__init__.py

When CTFd attempts to load a theme that has a numeric value as a name (ie. `2020`), it will toss a `TypeError` exception, since `utils.get_config` automatically typecasted it to an `int`:
```
ctfd_1     | Traceback (most recent call last):
ctfd_1     |   File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base_async.py", line 56, in handle
ctfd_1     |     self.handle_request(listener_name, req, client, addr)
ctfd_1     |   File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/ggevent.py", line 160, in handle_request
ctfd_1     |     addr)
ctfd_1     |   File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base_async.py", line 107, in handle_request
ctfd_1     |     respiter = self.wsgi(environ, resp.start_response)
ctfd_1     |   File …
```

Fix typecasting exception when using utils.get_config to get theme

---

CTFd/__init__.py

Re-enable the Jinja LRU Cache by overriding the `Environment._load_template` function and adding a theme namespace. 
This is not a great solution but it's likely that this is causing a lot of slowdown because we're continually reparsing and compiling templates. 
We still cannot completely clear the jinja cache but this way theme changes don't trample each other. 
Closes #662

Re-enable the Jinja LRU Cache

---

CHANGELOG.md
CTFd/__init__.py
docs/conf.py
package.json

2.3.3 / 2020-04-12
**General**
* Re-enable the Jinja LRU Cache for **significant speedups** when returning HTML content
**API**
* `POST /api/v1/unlocks` will no longer allow duplicate unlocks to happen
* Makes `Account Visibility` subtext clearer by explaining the `Private` setting in Config Panel
**Themes**
* Fixes an issue with using a theme with a purely numeric name
* Fixes issue where the scoreboard graph always said Teams regardless of mode
**Miscellaneous**
* Bump max log file size to 10 MB and fix log rotation
* Docker image dependencies (apk & pip) are no longer cached reducing the image size slightly

Mark 2.3.3

---

CTFd/api/v1/teams.py
CTFd/api/v1/tokens.py
CTFd/api/v1/users.py
CTFd/utils/logging/__init__.py
CTFd/utils/security/auth.py
CTFd/utils/user/__init__.py
tests/challenges/test_dynamic.py
tests/helpers.py
tests/oauth/test_redirect.py

* Deprecates storing session["type"] as a means of referring to the user's current level. Instead you should refer to the database.
* Adds `CTFd.utils.user.get_current_user_type()` to get the current user's type or return None if the user is unauthed. 
* Closes #1279

Deprecates storing user type in session

---

CTFd/utils/config/__init__.py
CTFd/utils/email/smtp.py
Makefile
tests/users/test_auth.py
tests/utils/test_email.py

* Fix a potential issue where config.py SMTP settings might not have been overrideable from the Admin Panel
* Closes #1306 by using `email.message.EmailMessage` in Python 3. Python 2 will use the old `sendmail` behavior.

Add fix for SMTP server overriding and #1306

---

CTFd/constants/__init__.py
manage.py
tests/constants/test_constants.py

* Starts work on #929 
* Adds Enum classes that can be accessed from JS, Jinja, and Python code. This allows for the sharing of constant values between the three major codebases in CTFd.

Better constant value management

---

CTFd/cache/__init__.py
CTFd/utils/initialization/__init__.py
CTFd/utils/user/__init__.py
tests/admin/test_config.py

User IPs should be cached for most actions but not updated without some kind of user action. 
* Cache user IPs and only update IP usage on new IPs or on non-GET requests

Start to refactor tracker to cache user IPs

---

CHANGELOG.md
CTFd/__init__.py
docs/conf.py
package.json

2.4.1 / 2020-05-06
* Fix issue where admins couldn't update the "Account Creation" email
* Fix issue where the Submissions page in the Admin Panel could not be paginated correctly
**Miscellaneous**
* Add `SQLALCHEMY_ENGINE_OPTIONS` to `config.py` with a slightly higher default `max_overflow` setting for `SQLALCHEMY_MAX_OVERFLOW`. This can be overridden with the `SQLALCHEMY_MAX_OVERFLOW` envvar
* Add `node_modules/` to `.dockerignore`

Mark v2.4.1

---

CTFd/utils/exports/__init__.py
CTFd/utils/initialization/__init__.py

* Improve `import_ctf()` reliability by closing all connections before dropping & recreating database
* Close database session in IP tracking code in failure situations

Improve import_ctf reliability

---

CTFd/utils/exports/__init__.py

* Don't allow backups to be imported if they do not have a `db` folder
* Closes #1422

1422 block imports without db folder

---

CTFd/utils/exports/__init__.py

* Use a `ThreadPoolExecutor` to concurrently store files during import
I see some slight speed improvements here:
```
old code
28.60257339477539
33.722084283828735
new code
22.658297300338745
20.487057209014893
```

Use a ThreadPoolExecutor to concurrently store files during import

---

CTFd/api/v1/challenges.py
CTFd/api/v1/teams.py
CTFd/api/v1/users.py
tests/api/v1/test_challenges.py
tests/api/v1/test_teams.py
tests/api/v1/test_users.py

* Add `view=admin` GET param to `/api/v1/users`, `/api/v1/teams`, and `/api/v1/challenges` to bypass filtering for admins
* Closes #1423 #1445
* Related to #1165

1423 model filter bypass

---

migrations/README
migrations/env.py
requirements.txt

* Update Flask-Migrate to 2.5.3
* Regenerate the `env.py` file for migrations and delete useless README file
* Supercedes #1447

Update Flask-Migrate and regenerate the migration env

---

CTFd/cache/__init__.py
CTFd/models/__init__.py

* Cache Users.get_score and Users.get_place. Clear on `clear_standings()`
* Cache Teams.get_score and Teams.get_place. Clear on `clear_standings()`
This caches the score and place attributes of users with the aim of speeding up the `/api/v1/scoreboard` views.

Cache User & Team score and place

---

CHANGELOG.md
CTFd/api/v1/scoreboard.py
CTFd/models/__init__.py
CTFd/utils/scores/__init__.py

* Improve response times of `/api/v1/scoreboard` significantly by avoiding hitting the database to get every team member's score
* Fix issue where a hidden/banned user's score could be revealed as a member of a team
From tests I was able to cut this down from 11s to 0.5s. This endpoint also will still be heavily cached which should improve performance for a lot of users.

Improve response times of /api/v1/scoreboard significantly

---

CHANGELOG.md
Dockerfile

* Closes #1472 
```
docker build --no-cache -t ctfd .
docker run -p 8000:8000 -it ctfd
```
works for me

Python 2 has been removed from Alpine so install Python 3 deps in Alpine

---

CHANGELOG.md
CTFd/api/v1/scoreboard.py

* The top scoreboard endpoint `/api/v1/scoreboard/top/<count>` is now more performant (3x) due to better response generation
In local testing I went from 3.5s to 1.2s.

Scoreboard optimizations

---

CTFd/utils/scores/__init__.py

* Make `get_standings` code more flexible by allowing to specify what other attributes to add into query. 
* Closes #1020

 Make `get_standings` code more flexible by allowing to specify what other attributes to add into query. 

---

CTFd/constants/config.py
CTFd/utils/__init__.py
CTFd/utils/config/visibility.py
CTFd/utils/decorators/visibility.py
CTFd/utils/initialization/__init__.py
CTFd/views.py

* Adds Enums for visibility configs for better reusability. Old tests will continue to use the static values but new ones should use the enum values. 
* Closes #929

929 better visibility constants

---

CTFd/__init__.py

get_source expects the third return value to be callable
see documentation: https://jinja.palletsprojects.com/en/2.11.x/api/#jinja2.BaseLoader.get_source
this happened after https://github.com/CTFd/CTFd/commit/320feb91796f2eba538eef48c338fb37ade980d2 because the commit enabled the cache, and thus calling `up_to_date` surfaces the issue

[fix #1503] override_template cache error

---

CTFd/constants/teams.py
CTFd/constants/users.py
CTFd/utils/initialization/__init__.py

* Adds User and Team globals to Jinja theme files. 
* Closes #1234 
This should allow for more sharing from the Python code to Jinja and thus to JS allowing for easier theme development.

Add User and Team Jinja globals to access User/Team attrs

---

CTFd/api/v1/schemas/__init__.py
CTFd/api/v1/submissions.py
CTFd/api/v1/teams.py
CTFd/api/v1/users.py

* Paginate only the `/api/v1/users`, `/api/v1/teams`, and `/api/v1/submissions` endpoints.
* Add a `PaginatedAPIListSuccessResponse` class with a customized `apidoc` method to hack in the pagination scheme
* Works on #1318

1318 pagination users teams submissions

---

CTFd/admin/challenges.py
CTFd/api/v1/challenges.py
CTFd/errors.py
CTFd/models/__init__.py
CTFd/themes/core/templates/errors/500.html
tests/challenges/test_challenge_types.py

* Handle missing challenge types better by letting challenges fall back to the main Challenges model. This lets us better detect when a challenge type isn't loaded but exists in the database. 
* Closes #1526

Handle missing challenge types better.

---

CTFd/plugins/dynamic_challenges/assets/view.js

The reason this happens is because the view.js in this plugin uses #submission-input as id for the input field when it's in fact #challenge-input.
* Closes #1542

Fix error on flag submission when using dynamic challenge.

---

CHANGELOG.md
CTFd/__init__.py
package.json

**General**
- Make HTML Sanitization an optional setting that's configurable via `HTML_SANITIZATION` in config.ini
- Allow HTML comments through sanitization
- Allow Bootstrap data attributes through sanitization
- Fix an unclickable label in the Challenge creation interface
**Plugins**
- Fix bug preventing deleting alternative challenge types
**Miscellaneous**
- Switch to using Github Actions for testing and linting

Mark 3.0.0b2

---

CTFd/__init__.py
CTFd/utils/updates/__init__.py
Makefile
development.txt
tests/utils/test_updates.py

* Add a channel key to update check and use a new GET based update check endpoint
* Bump `black` version to `19.10b0`

Add channel to update check and use new endpoint

---

CTFd/api/v1/helpers/request.py

* Return better errors on invalid API parameters
For example:
```
{
"success": false,
"errors": {
"user_id": "value is not a valid integer"
}
}
```

Return better errors on invalid API parameters

---

CHANGELOG.md
CTFd/__init__.py
README.md
package.json

The CTFd v3 Changelog represents the changes from v2.5.0 to v3. It is a summarized version of the changes that occured in all CTFd v3 beta/alpha releases.
CTFd v3 contains some breaking changes but many plugins remain compatible. Themes will need some minor changes to be compatible with v3.
These changes are made with great consideration to existing installations and for the health of the overall CTFd project. If you rely on specific behavior, you can always download the last CTFd v2 release on Github. Official plugin/theme updates will be sent to the email addresses on file.
The major changes in CTFd v3 are as follows with the detailed changelog beneath:
- ### Server Side HTML/Markdown Rendering
HTML rendering in some cases (challenge description rendering, hint content rendering) has …

Mark 3.0.0

---

CTFd/config.ini
CTFd/config.py

* Make config.ini properly supercede environment variables
* Add ability for all config.ini values to fallback to environment variables. 
* Closes #1573 
Config Behavior should be as follows:
1. Key exists in `config.ini` and is set to a value. That value becomes the app config.
2. Key exists in `config.ini` but is set to empty string. An envvar the same name is looked up. The envvar's value is used as the app config. 
3. If the envvar is not found, fall back to the default specified value in `config.py`
4. If there is no default, use None or an empty string

Add a better fallback for environment variables through config interpolation

---

CTFd/scoreboard.py
CTFd/utils/decorators/visibility.py
tests/admin/test_scoreboard.py

* Fix issue where admins could not see user graphs/api data if score visibility was set to hidden
* Closes #1580

1580 fix hidden admin scores

---

CTFd/admin/submissions.py
CTFd/api/v1/awards.py
CTFd/api/v1/challenges.py
CTFd/api/v1/config.py
CTFd/api/v1/files.py
CTFd/api/v1/flags.py
CTFd/api/v1/helpers/models.py
CTFd/api/v1/hints.py
CTFd/api/v1/notifications.py
CTFd/api/v1/pages.py
CTFd/api/v1/submissions.py
CTFd/api/v1/tags.py
CTFd/api/v1/teams.py
CTFd/api/v1/unlocks.py
CTFd/api/v1/users.py
CTFd/forms/submissions.py
CTFd/models/__init__.py
CTFd/themes/admin/templates/challenges/challenge.html
CTFd/themes/admin/templates/submissions.html
CTFd/utils/helpers/models.py

* Allow the Admin Panel Submissions page to filter by Account IDs, Challenge IDs, and Challenge Names
* Deprecate `CTFd.api.v1.helpers.models.build_model_filters` and wrap it to `CTFd.utils.helpers.models.build_model_filters`
* Clean up some miscellaneous Submissions code 
* Closes #1569

1569 submission filter by challenge

---

CHANGELOG.md
CTFd/__init__.py
package.json

**General**
- Fix issue where admins could not see user graphs/api data if score visibility was set to hidden
- Allow the Admin Panel Submissions page to filter by Account IDs, Challenge IDs, and Challenge Names
- Link to correct submissions for challenge from the challenge page
**API**
- Fix regression for creating hints via ctfcli. See #1582 for details. https://github.com/CTFd/CTFd/issues/1582.
- Deprecate `CTFd.api.v1.helpers.models.build_model_filters` and wrap it to `CTFd.utils.helpers.models.build_model_filters`
**Themes**
- Fix team pages to use the correct core errors component
**Plugins**
- Fix issues with previewing challenges under some challenge type plugins
**Deployment**
- Values specified in `config.ini` will now supercede values specified via environment …

Mark 3.0.1

---

CTFd/api/v1/comments.py
CTFd/forms/teams.py
CTFd/schemas/teams.py
CTFd/themes/core/templates/teams/private.html
tests/api/v1/test_teams.py

* Loosen team password confirmation to also accept team captain password
* Make team settings modal larger in the core theme
* Add help text in team settings form
* Closes #1545

Loosen team password confirmation to also accept team captain password

---

CTFd/config.py

`empty_str_cast` allows for a default value. This is probably how defaults should be managed. The current logic is definitely incorrect for `true` defaults, since when trying to override it to `false`, it ultimately resolves to `false or true`, which is `true`.

Fix config default logic

---

requirements.txt

The gevent version 20.5.2 is not compatible with greenlet generating a Runtime error and not letting the CTFd start. 
This PR fixes Issue #1667 
This was fixed by gevent version bump.The version 20.9.0 works fine.

Bump gevent version

---

docker-compose.yml

Hi,
The restart policy for nginx is different than the rest of the challenges. Because the default restart policy is `no`, this causes `nginx` to not restart automatically (like after a reboot), while other challenges do.

Fix Docker Compose restart policy

---

development.txt

* Remove `psycopg2` dep and only use `psycopg2-binary`
* Update `psycopg2-binary` to 2.8.6

Remove psycopg2 dep and only use psycopg2-binary

---

requirements.txt

* Build `requirements.txt` on Python 3.7 to fix an issue with installing dataclasses. 
* Closes #1729 
I tested that this works in Python 3.6, 3.7, and 3.8. A useful project would be to add installing deps to Github Actions. 
I'll subscribe to https://github.com/ericvsmith/dataclasses/pull/161 since this is IMO a bug in dataclasses.

Fix requirements for Python 3.7 

---

CTFd/config.ini

Setting `filesystem` here actually prevent the config to be overwritten by an environment variable. This prevent stateless setup such as running CTFd from the official docker image.
This is not a breaking change since the `UPLOAD_PROVIDER` config already has `filesystem` as fallback in `CTFd/config.py` and `CTFd/utils/uploads/__init__.py`.
PS: I've used Github to create the patch and it automatically added a new line at the end of the file, I haven't removed it as it is best practise anyway.

No longer set "filesystem" as UPLOAD_PROVIDER in config.ini

---

CHANGELOG.md
CTFd/plugins/migrations.py
CTFd/utils/exports/__init__.py

- The plugin `upgrade()` function now accepts a `lower` parameter which specifies what lower revision should be used to start from.
- This is used to support plugin migrations during import so that we can import data directly at the point that the import was taken from
- `lower="current"` means to use the current revision and `lower=None` would mean to use the absolute base revision (e.g. plugin's first installation)
- By default this doesn't change `upgrade()` behavior

Add a lower parameter to the plugin upgrade() function to help importing

---

Dockerfile

This change first copies and sets up the python requirement file and only then copies the rest of the working directly.
This change can speed up docker rebuilds in a dev or CI environment as code changes that do not impact requirements.txt will not force redownloading all the python dependencies.

Speed up docker builds

---

CTFd/api/v1/challenges.py
tests/api/v1/test_challenges.py
tests/api/v1/test_teams.py

This changeset reworks the challenge list API endpoint to count the
number of solves for each challenge and whether the current user (or
their team) have already solved it. The endpoint now return two new keys
per item in the response; the `solved` boolean which shows if the
challenge has been solved already, and the `total_solves` integer which
shows how many solves have been made by all users.
Closes #1811

feat: Add solve count and status to challenge list

---

CTFd/api/v1/scoreboard.py
CTFd/utils/scores/__init__.py

* Experiment with a faster way to generate the scores of all members in the /api/v1/scoreboard endpoint

Experiment with a faster /api/v1/scoreboard endpoint

---

CTFd/__init__.py
CTFd/constants/themes.py
CTFd/themes/admin/templates/configs/theme.html
CTFd/utils/plugins/__init__.py
tests/test_themes.py

This change reworks the template loaders so that we make more liberal
use of the ordered preferential loading provided by `ChoiceLoader` to
simplify the `ThemeLoader` so it only needs to be aware of a single
theme name to load templates from. This allows us to more easily
implement loading of templates from specific themes by providing an
extra `PrefixLoader` which is aware of all of the themes available to
the application.

refac: Allow loading theme templates by prefix

---

CTFd/challenges.py
tests/teams/test_challenges.py

* Don't require a team for viewing challenges if Challenge visibility is set to public
* Closes #1831

Relax team requirement when challenges are publicly visible

---

CHANGELOG.md
CTFd/themes/core/templates/users/private.html
CTFd/themes/core/templates/users/public.html

* Fix an issue where hidden users couldn't see their graphing data on their private user page (i.e. `/user`)

Fix for hidden users seeing their graphing data

---

.dockerignore
CHANGELOG.md

- Add `.pyc` files and `__pycache__` to `.dockerignore`

Add pyc and pycache files to dockerignore

---

CHANGELOG.md

**General**
- Don't require a team for viewing challenges if Challenge visibility is set to public
- Add a `THEME_FALLBACK` config to help develop themes. See **Themes** section for details.
**API**
- Implement a faster `/api/v1/scoreboard` endpoint in Teams Mode
- Add the `solves` item to both `/api/v1/challenges` and `/api/v1/challenges/[challenge_id]` to more easily determine how many solves a challenge has
- Add the `solved_by_me` item to both `/api/v1/challenges` and `/api/v1/challenges/[challenge_id]` to more easily determine if the current account has solved the challenge
- Prevent admins from deleting themselves through `DELETE /api/v1/users/[user_id]`
- Add length checking to some sensitive fields in the Pages and Challenges schemas
- Fix issue where `PATCH …

Mark 3.3.0

---

.dockerignore

- Make `node_modules` in `.dockerignore` recursive to not add any `node_modules` folders into the build context

Ignore node_modules in any subdirectory for Docker

---

CTFd/utils/countries/geoip.py

Added error handling in case `IP_ADDR_LOOKUP.get(addr)` fails. I'm not entirely sure what caused this issue in my installation, but it manifested as an empty string being passed in as addr. the exception that was raised caused admins to not be able to manage any users.

GeoIp bugfix

---

CTFd/api/v1/challenges.py

When you go over 256 (?) challenges, the sorting of everything gets chaotic. Before that threshold, everything seems to be implicitly secondarily sorted by id (probably just an artifact of the database internals). A nice and simple fix is to just sort everything by id explicitly as a secondary sorting key. For most users, this should not have any effect. For the (probably rare) users that go over this 256 barrier, this will make things function as expected.

Sort challenges by id

---

CTFd/models/__init__.py
tests/test_plugin_utils.py

* Add a way to access the challenge plugin class from the Challenges model
* Allows templates to access the plugin class more easily
* Allows plugins to access the plugin class without having to load the class explicitly
* Closes #1879

Add a way to access the challenge plugin class from the Challenges model

---

CTFd/api/v1/config.py
CTFd/schemas/config.py
tests/api/v1/test_config.py

* Properly receive non-string config values (None, bool, integers, etc) in /api/v1/config
* Closes #1928 
* Fix the response schema for `PATCH /api/v1/configs/<config_key>` in error situations
Overall we weren't particularly strict before and we should try to stay a little lax so we don't break anything.

Add a fix for receiving non-string Config values

---

CTFd/themes/core/templates/settings.html

* Works on #1891 
* Hides token type from user settings because it's currently unused

Hide token type in user settings

---

CHANGELOG.md
CTFd/__init__.py
package.json

**Security**
- Fixes an issue where users could join teams without knowing the team password or having a team invite

Mark 3.3.1

---

CHANGELOG.md
CTFd/config.ini
CTFd/config.py
tests/test_themes.py

* CTFd now has the `THEME_FALLBACK` option enabled by default. This allows users to provide incomplete themes. Missing theme files will be provided from the built-in core theme
* Closes #1967

Set THEME_FALLBACK to default to true

---

CTFd/forms/config.py

Changed `capatins` to `captains`

Fix typo under Admin Config > Accounts > Team Disbanding

---

CHANGELOG.md
CTFd/__init__.py
package.json

**General**
- Added the ability to have Challenge Topics
- Challenge Topics are small topic strings which are only visible to Admins
- They should denote what topics a given challenge involves
- Added `connection_info` to Challenges to allow Admins to more easily specify the connection info for a challenge
- Added ability to import CSVs of users, teams, and challenges
- Added ability to limit the total number of teams
- Pages now have access to variables `ctf_name`, `ctf_description`, `ctf_start`, `ctf_end`, `ctf_freeze`. (e.g. `{{ ctf_name }}`)
- IP Addresses in the Admin Panel will now show the city of the IP address as well as the country
- Make User Mode it's own dedicated tab in the setup flow and more clearly explain what each user mode does
- Added the ability to have a …

Mark v3.4.0

---

CTFd/schemas/submissions.py

* Add nested UserSchema and TeamSchema to SubmissionSchema to allow easier access to a user/team name without issuing another query/API call
* Closes #2005

Add nested UserSchema and TeamSchema to SubmissionSchema

---

CHANGELOG.md
CTFd/api/v1/challenges.py

* Improve speed of the ChallengeSolves API (`/api/v1/challenges/[challenge_id]/solves`) endpoint
From time testing there is a significant improvement:
Before:
```
690 ms ± 47.5 ms per loop (mean ± std. dev. of 10 runs, 3 loops each)
684 ms ± 45.1 ms per loop (mean ± std. dev. of 10 runs, 3 loops each)
712 ms ± 79 ms per loop (mean ± std. dev. of 10 runs, 3 loops each)
761 ms ± 108 ms per loop (mean ± std. dev. of 10 runs, 3 loops each)
```
After:
```
125 ms ± 25.6 ms per loop (mean ± std. dev. of 10 runs, 3 loops each)
115 ms ± 7.94 ms per loop (mean ± std. dev. of 10 runs, 3 loops each)
127 ms ± 17.6 ms per loop (mean ± std. dev. of 10 runs, 3 loops each)
133 ms ± 27.2 ms per loop (mean ± std. dev. of 10 runs, 3 loops each)
```
We should consider the potential performance gains vs risks …

Improve speed of the ChallengeSolves API endpoint

---

CHANGELOG.md
CTFd/__init__.py

**General**
- Make session cookies persist in the browser after close
- Fix issue where all-numeric registration codes wouldn't work
- Fix issue where a user's session isn't cleared properly after they are deleted by an admin
- Fix issue where CTF end time couldn't be set during setup
**API**
- Improved speed of the `/api/v1/challenges/[challenge_id]/solves` endpoint
- Document API authentication and `Content-Type` header requirement
- Add nested `UserSchema` and `TeamSchema` to `SubmissionSchema` for easier access to account name
- Improve CSV import error reporting and validation
- Fix non-clickable checkbox label in user creation form in Admin Panel
- Allow submissions per minute ratelimit to be configurable in Admin Panel
- Add a link in the Pages Editor to the [Page …

Mark 3.4.1

---

CHANGELOG.md
CTFd/__init__.py
package.json

**Security**
- Bump cmarkgfm to 0.8.0 to resolve CVE-2022-24724
**General**
- Fix issue where unauthed users couldn't download challenge files after CTF end but viewing after CTF was enabled

Mark 3.4.2

---

CHANGELOG.md
CTFd/__init__.py
CTFd/utils/__init__.py
package.json
tests/utils/test_markdown.py

**Security**
- Bump cmarkgfm to 0.8.0 to resolve CVE-2022-24724. Copied entry from 3.4.2 since 3.4.2 introduced a bug that prevented writing raw HTML.
**General**
- Fix issue where raw HTML would not be rendered in markdown

Mark 3.4.3

---

CTFd/utils/sessions/__init__.py
tests/utils/test_sessions.py

* Add code to check for the potential of session ID duplication during ID generation

Add code to check for the potential of session ID duplication during ID generation

---

docker-compose.yml

As discussed in #2086, this PR changes the docker-compose file to automatically uses the latest version of Nginx instead of a pinned version.

Docker-compose now always uses stable nginx

---

CTFd/themes/admin/templates/import.html
CTFd/utils/exports/__init__.py
CTFd/utils/exports/databases.py
CTFd/utils/exports/serializers.py
manage.py

* Closes #2087 
* Use `python manage.py import_ctf` instead of a new Process to import backups from the Admin Panel. 
* This avoids a number of issues with gevent and webserver forking/threading models. 
* Add `--delete_import_on_finish` to `python manage.py import_ctf`
* Fix issue where `field_entries` table could not be imported when moving between MySQL and MariaDB

Fix issues with backup importing

---

CHANGELOG.md
CTFd/__init__.py
package.json

**General**
- Add a next challenge recommendation to challenges
- Add support for only viewing hints after unlocking another hint
- Add size checking and recommendation for images uploaded during setup
- Imports now happen in the background so that admins can watch the status of the import
- Add progress tracking to backup/export importing
- Add `GET /admin/import` to see status of import
- The public user facing portion of CTFd is now disabled during imports
- Fix issue where custom field entries for Users and Teams would be misaligned in the scoreboard CSV export
- Show admins the email server error message when email sending fails
- Fix issue where the current theme cannot be found in list of themes
- Fix page preview so that it accounts for the provided format
**API** …

Mark 3.5.0

---

CTFd/themes/core/templates/settings.html

`delete` space

---

CTFd/challenges.py
CTFd/utils/decorators/visibility.py

Added info stating "Challenges are set to Admins Only mode" for admins in relevant case so they don't forget as per issue https://github.com/CTFd/CTFd/issues/2137.

Added info for challenges page Admins Only mode

---

CTFd/utils/exports/__init__.py

* Fix issue where `field_entries` could not be imported under MariaDB
* Fix issue where `config` entries sometimes would be recreated for some reason causing an import to fail

Fix miscellaneous issues for importer

---

CTFd/schemas/teams.py
CTFd/schemas/users.py

When a checkbox field that is required and editable is created after user has created account. Existing users are unable to update their profile as an internal server error is produced.
The internal server error is due to the required field being a boolean and .strip() is invoked on a boolean with causes an error.
The fix is to validate the type of value to be string before checking if the field is empty.

validate value type is string before using strip

---

CTFd/themes/admin/templates/challenges/challenges.html
CTFd/themes/admin/templates/notifications.html
CTFd/themes/admin/templates/pages.html
CTFd/themes/admin/templates/scoreboard/standings.html
CTFd/themes/admin/templates/scoreboard/users.html
CTFd/themes/admin/templates/submissions.html
CTFd/themes/admin/templates/teams/team.html
CTFd/themes/admin/templates/teams/teams.html
CTFd/themes/admin/templates/users/user.html

* Add `autocomplete='off'` to admin pages to fix Firefox caching checkboxes

Add autocomplete='off' to admin pages to fix Firefox caching checkboxes

---

CTFd/utils/plugins/__init__.py

Made get_configurable_plugins work nicely with config.jsons that include multiple plugin entries as a list. 
I do not take credit for this as John Hammond did this and I just did not want to do this every time I clone the project.

 Made get_configurable_plugins work with multiple plugin entries as a list

---

package.json

When running software installed via NPM, `node_modules/.bin` is in PATH, so we can just omit most of the path.

Use binaries in PATH in npm run scripts

---

CTFd/api/v1/notifications.py
CTFd/utils/events/__init__.py
tests/utils/test_events.py

* Improve event `ping`s to actually include data so that they show up in devtools
* Improve Event publishers to take an `id` parameter that is sent to the browser
* Add a `since_id` parameter to `GET /api/v1/notifications` to get Notifications that have happened since a specific ID
* Add `HEAD /api/v1/notifications` to get a count of notifications that have happened. This also includes a `since_id` parameter to allow for a notification cursor.

Notifications improvements

---

CTFd/plugins/migrations.py

* Specifically load a plugin's alembic_version from the database to bypass the cache

Specifically load a plugin's alembic_version from the database

---

.github/workflows/docker-build.yml

Adds ARM docker builds, switches from using a PAT to GitHub tokens for GHCR, and cleans up the docker CI/CD action.

Update Docker Image CI/CD

---

CTFd/utils/decorators/__init__.py
tests/utils/test_ctftime.py

This change redirects users to the team creation page if they access a during_ctf_time_only page before the CTF starts. This results in a better experience since users can start assembling their team immediately.

Redirect users to team creation before event start

---

CTFd/config.ini
CTFd/config.py
CTFd/utils/uploads/uploaders.py
tests/utils/test_uploaders.py

This is a fix for https://github.com/CTFd/CTFd/issues/2115 .
**Changes summary:**
- Adds a `AWS_S3_REGION` configuration key in `config.ini` and `config.py`.
- Passes the corresponding value as the S3 region when creating the boto3 client for the S3 uploader. Boto3 will default to `us-est-1` the value is `None`, conserving the current behavior if the configuration key is not set.
- Includes a test region in unit tests.
Credits to @mh4ckt3mh4ckt1c4s for the discovery of the issue and a first version of the fix.

Add support for custom S3 regions in S3 uploader

---

CTFd/utils/initialization/__init__.py

This PR fixes #2214 by adding a `/healthcheck` endpoint to the application.
Tested and working
```text
172.17.0.1 - - [04/Nov/2022:11:43:02 +0000] "GET /themes/core/static/js/pages/setup.min.js?d=67acada5 HTTP/1.1" 200 0 "http://0.0.0.0:8000/setup" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36"
172.17.0.1 - - [04/Nov/2022:11:43:02 +0000] "GET /events HTTP/1.1" 302 219 "http://0.0.0.0:8000/setup" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36"
172.17.0.1 - - [04/Nov/2022:11:43:02 +0000] "GET /themes/core/static/img/favicon.ico?d=67acada5 HTTP/1.1" 200 0 "http://0.0.0.0:8000/setup" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 …
```

Allow `/healthcheck` endpoint to bypass setup 

---

CTFd/utils/exports/__init__.py
CTFd/utils/initialization/__init__.py
CTFd/utils/migrations/__init__.py

* Be more defensive on asset loading during imports
* On primary databases only import backups when we are actually able to make it to the target migration

Adding more protections for 502's during imports

---

CTFd/config.ini
CTFd/config.py
CTFd/utils/config/__init__.py
CTFd/utils/email/__init__.py
CTFd/utils/email/mailgun.py
CTFd/utils/email/providers/__init__.py
CTFd/utils/email/providers/mailgun.py
CTFd/utils/email/providers/smtp.py
CTFd/utils/email/smtp.py

* Change sendmail functions into classes that can be overriden from a plugin
* Deprecate `CTFd.utils.email.mailgun.sendmail`
* Deprecate `CTFd.utils.email.smtp.sendmail`

Change sendmail functions into classes that can be overriden from a plugin

---

requirements.in
requirements.txt

Bump bcrypt, gevent, greenlet, python-geoacumen-city, requests.
There are probably more dependencies that need to be updated.
The update is important because new versions of gevent and greenlet support musl.
In the future I will create another docker image based on alpine.
Alpine uses musl.

Bump CTFd dependencies

---

CTFd/scoreboard.py
CTFd/themes/admin/templates/configs/settings.html
CTFd/themes/core/templates/components/navbar.html

We need to make the discrepancy between score_visiblity and account_visibility clearer. 
I want to officially clarify score visibility as meaning: 
"If a user's account is visibile, do we then also show their score and solves?"
If you have account visibility but not score_visibility you should be able to see their account information but none of their score information. If you have score visibility but not account visibility you shouldn't be able to see anything. 
Score visibility should be seen as a subset of account visibility.
* Don't show `/scoreboard` if we do not have `account_visibility`

Clarify Score Visibility and Account Visibility

---

CTFd/admin/__init__.py
CTFd/api/v1/challenges.py
CTFd/api/v1/config.py
CTFd/api/v1/submissions.py
CTFd/api/v1/teams.py
CTFd/api/v1/users.py
CTFd/cache/__init__.py
CTFd/utils/challenges/__init__.py
populate.py
tests/api/v1/test_challenges.py
tests/cache/test_challenges.py
tests/helpers.py

* Improve response time of `/api/v1/challenges` and `/api/v1/challenges/[challenge_id]/solves`
* Rewrite and remove _build_solves_query to make it cacheable
* Closes #2209

Cache challenge data for faster loading of /api/v1/challenges

---

CTFd/config.ini
CTFd/config.py

This PR is meant to resolve issue #2231 by adding the following config settings:
- `DATABASE_PROTOCOL`: SQLAlchemy DB protocol (+ driver, optionally)
- `DATABASE_USER`: Username to access DB server with
- `DATABASE_PASSWORD`: Password to access DB server with
- `DATABASE_HOST`: Hostname of the DB server to access
- `DATABASE_PORT`: Port of the DB server to access
- `DATABASE_NAME`: Name of the database to use
As explained in the linked issue, these new settings are meant as an alternative to the monolithic `DATABASE_URL` setting, to allow each individual component to be controlled separately via environment variables.  
One of the main use cases is in cloud deployments, where it's common to treat the database credentials as opaque secrets, and store the rest of the connection details in …

Add individual DATABASE_* options, as an alternative to DATABASE_URL

---

CTFd/config.ini
CTFd/config.py

Expanding on #2237, this PR adds the following config settings:
- `REDIS_PROTOCOL`: Protocol to access Redis server with (either `redis` or `rediss`)
- `REDIS_USER`: Username to access Redis server with
- `REDIS_PASSWORD`: Password to access Redis server with
- `REDIS_HOST`: Hostname of the Redis server to access
- `REDIS_PORT`: Port of the Redis server to access
- `REDIS_DB`: Numeric ID of the database to access
As with my previous PR, `REDIS_URL` takes precedence over any of these new settings.
As far as I can tell, redis-py doesn't provide a helper similar to SQLAlchemy's URL class, so I used string concatenation to build the connection URL.
Unfortunately, connecting to a Unix Domain Socket with these settings is not supported, as the URL structure is very different.

Add individual REDIS_* options, as an alternative to REDIS_URL

---

CTFd/themes/admin/templates/configs/settings.html
CTFd/themes/admin/templates/configs/time.html

* Clean up the aesthetics for the 'Pause CTF' and 'View After CTF' configs
* Closes #2128 
I could not come up with a better place to put either of these configurations but I decided to clean up the content overall. I think they are okay where they are but if we get more time related configurations we can group them all together into one section. For now I think this is fine.

Clean up the aesthetics for the 'Pause CTF' and 'View After CTF' configs

---

CTFd/plugins/dynamic_challenges/__init__.py
CTFd/plugins/dynamic_challenges/assets/create.html
CTFd/plugins/dynamic_challenges/assets/update.html

* Fix issue where dynamic challenges break if the decay is 0
* Prevent users from adding a decay limit of 0 to dynamic value challenges

Fix issue where dynamic challenges break if the decay is 0

---

CTFd/utils/uploads/uploaders.py
development.txt
requirements.in
requirements.txt

* Add freezegun to application dependencies
* Generate cachable S3 URLs by rounding time down to the previous hour to generate a consistent URL

Add freezegun to runtime dependencies, generate cachable s3 urls

---

CTFd/config.py

* In some cases with numeric config items it appears that we can end up processing a string twice. This issue fixes it so that we only process the strings once at configparser load time with `before_get`

Fix issue where we are double processing config.ini items

---

CTFd/utils/health/__init__.py

In a high availability deployment scenario, two clients may make a request on /healthcheck at the exact same time, which can lead to check_config returning False if the second requests changes the 'healthcheck' cache key before the first one has had time to fetch the value it had set.
A solution to counter this is to ensure different keys are used for each healthcheck.

Prevent race conditions on /healthcheck

---

CTFd/__init__.py
CTFd/admin/__init__.py
CTFd/api/v1/challenges.py
CTFd/api/v1/statistics/__init__.py
CTFd/auth.py
CTFd/cache/__init__.py
CTFd/models/__init__.py
CTFd/plugins/migrations.py
CTFd/utils/initialization/__init__.py
CTFd/utils/user/__init__.py
CTFd/views.py
Makefile
development.txt
migrations/env.py
migrations/versions/0366ba6575ca_add_table_for_comments.py
migrations/versions/07dfbe5e1edc_add_format_to_pages.py
migrations/versions/46a278193a94_enable_millisecond_precision_in_mysql_.py
migrations/versions/4d3c1b59d011_add_next_id_to_challenges_table.py
migrations/versions/6012fe8de495_add_connection_info_column_to_challenges.py
migrations/versions/75e8ab9a0014_add_fields_and_fieldentries_tables.py
migrations/versions/a03403986a32_add_theme_code_injections_to_configs.py
migrations/versions/ef87d69ec29a_add_topics_and_challenge_topics_tables.py
tests/cache/test_challenges.py
tests/constants/test_constants.py

I've removed `flake8` from dependencies and put `ruff` instead. Also replaced the command in `lint` part in the makefile.
In ruff, I wasn't able to find the equivalent rules for `W503` and `E203`. So I've removed these ignores from ruff as well. I've avoided using a `.ruff.toml` file for the configuration.
I haven't removed `flake8-isort` from `development.txt` in case it's used by `isort`. Unless it's used it can be removed too.
This PR resolves issue #2263

use ruff instead of flake8

---

CTFd/themes/admin/templates/configs/email.html

Replaced TLS and SSL checkbox text to match the
defaults used by Mozilla Thunderbird to eliminate confusion when configuring SMTP.
https://github.com/CTFd/CTFd/issues/2292

SMTP TLS/SSL Labels to Match Thunderbird

---

CTFd/themes/core-beta/templates/teams/private.html

* Fix issue where the private team page would not render properly
Make sure to use Merge Commits when dealing with the subtree here. For some reason Github's squash and commit uses the wrong line ending which causes issues with the subtree script: https://stackoverflow.com/a/47190256.

Pull core beta

---

conf/nginx/http.conf

This enables gzip for nginx.
Without gzip, our scoreboard takes 5 mb and with gzip, ~100kb.

Enable gzip for nginx

---

CTFd/api/v1/hints.py
CTFd/models/__init__.py
tests/api/v1/user/test_hints.py

* Free hints (those without a cost or prerequsitites) can now be viewed publicly if challenges are visible publicly
* Closes #2157

Make free hints visible to unauth users if challenges are visible to unauth users

---

requirements.in
requirements.txt

This dependency is required to allow compatibility with MySQL instances that enforce specific authentication protocols. This is often the case with managed databases for some public cloud providers. PyMySQL documentation: https://pymysql.readthedocs.io/en/latest/user/installation.html .
Tested on OVHcloud public cloud through the [404 CTF](https://www.404ctf.fr) .

Add the optional rsa dependency to pymysql

---

docker-entrypoint.sh

While the `ping.py` script is useful in most scenario, it can be bothersome when troubleshooting database issues in complex, container based environments, especially because it will not print out the actual exception when the database is ready but the connection fails for another reason. Additionally, such environments, like Kubernetes, may offer better alternative, like running the `ping.py` in a dedicated init container.
For those reasons, it might often be useful to not run `ping.py` when the CTFd container starts up. This pull request adds options to disable it.
- An environment variable, `CHECK_DB`, which can be set to `false` to disable `ping.py`.
- A flag, `--no-check-db`, which can be passed as an argument to `docker-entrypoint.sh`, to achieve the same result (takes precedence).

Option to not wait for the datababase on Docker

---

docker-entrypoint.sh

* Add new envvar `SKIP_DB_PING` to instruct the CTFd Docker image to not test if the database server is available

Add SKIP_DB_PING to skip database availability test

---

CTFd/__init__.py
CTFd/cli/__init__.py
CTFd/utils/initialization/__init__.py
manage.py

* Fix manage.py to work with Flask CLI 
* Support both the legacy `manage.py` CLI as well as the new `flask` CLI
* Closes #2354
* Closes #2352

Upgrading manage.py to work with Flask 2.0

---

ping.py

Problem: when starting CTFd with an empty database the ping check will fail, complaining that the database does not exist. Calling `set` with parameter value `None` does not actually remove the value from the connection string. 
Solution: Rewrite as explained in the `set` method documentation.
Excerpt from the documentation:
```
Values are used if they are non-None.  To set a value to ``None``
explicitly, use the :meth:`_engine.URL._replace` method adapted
from ``namedtuple``.
```

Fix remove db from connection string

---

CTFd/forms/config.py
CTFd/utils/email/__init__.py
tests/utils/test_email.py

This allows to specify domains with a wildcard like `*.edu` for the domain whitelist.
Note that this is not a regex match, it doesn't evaluate the expression to support inner wildcards, e.g. it's not possible do do something like `cs.*.edu` - however that's intentional to keep this simple.

Add email whitelist wildcard

---

CTFd/models/__init__.py

* Fix SQLAlchemy warning about back_populates
```
flask_sqlalchemy/__init__.py:550: SAWarning: relationship 'UserFieldEntries.user' will copy column users.id to column field_entries.user_id, which conflicts with relationship(s): 'Users.field_entries' (copies users.id to field_entries.user_id). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards.   To silence this warning, add the parameter 'overlaps="field_entries"' to the 'UserFieldEntries.user' relationship. (Background on this error at: …
```

Fix SQLAlchemy warning about back_populates

---

CTFd/auth.py
CTFd/forms/teams.py
CTFd/forms/users.py
CTFd/teams.py

* Fix issue where a custom field named affiliation or website prevents registration
* No longer special case "Affiliation" or "Website" as custom field titles
We don't special case affiliation or website anymore as we will look to remove these fields and make them custom fields. By removing the special casing admins have more control over what field they specifically want to collect and show. Similarly if admins want to require Affiliation or Website on registration there exists the field collection that happens for the registration fields:
```python
website = request.form.get("website")
affiliation = request.form.get("affiliation")
country = request.form.get("country")
```

Fix issue where a custom field named affiliation or website prevents registration

---

CTFd/__init__.py
CTFd/admin/__init__.py
CTFd/utils/uploads/uploaders.py
CTFd/views.py
requirements.in
requirements.txt
tests/admin/test_views.py
tests/api/v1/user/test_admin_access.py
tests/oauth/test_redirect.py
tests/teams/test_challenges.py
tests/test_themes.py
tests/test_views.py
tests/users/test_auth.py
tests/users/test_fields.py
tests/users/test_setup.py
tests/utils/test_sessions.py

* Downgrade Werkzeug from 2.1.2 to 2.0.3 to avoid removal errors
* Fix warnings from Werkzeug migration from v1 to v2
Revert test changes from #2332:
```
git checkout 7b68babee616a26e372a2883f3144754909c66ca -- tests/teams/test_challenges.py
git checkout 7b68babee616a26e372a2883f3144754909c66ca -- tests/users/test_setup.py
git checkout 7b68babee616a26e372a2883f3144754909c66ca -- tests/users/test_auth.py
git checkout 7b68babee616a26e372a2883f3144754909c66ca -- tests/test_themes.py
git checkout 7b68babee616a26e372a2883f3144754909c66ca -- tests/utils/test_sessions.py
git checkout 7b68babee616a26e372a2883f3144754909c66ca -- tests/admin/test_views.py
git checkout 7b68babee616a26e372a2883f3144754909c66ca -- tests/oauth/test_redirect.py
git checkout 7b68babee616a26e372a2883f3144754909c66ca -- …
```

Downgrade Werkzeug from 2.1.2 to 2.0.3 to avoid removal errors

---

CTFd/events/__init__.py
CTFd/utils/events/__init__.py
requirements.in
requirements.txt

* Bump PyMySQL to 1.0.2
* Simply event timeout ping as discussed here: https://www.gevent.org/api/gevent.timeout.html
* Close db connections in the event handler route

Bump pymysql version to 1.0.2 and simplify event timeout ping

---

CTFd/api/v1/teams.py
CTFd/api/v1/users.py
tests/api/v1/teams/test_teams.py
tests/api/v1/users/test_users.py

* Allow user/team emails to be queried via API by admin users
* Add `email` as an acceptable `field` to query to `/api/v1/users` and `/api/v1/teams`

Allow user/team emails to be queried via API by admin users

---

CTFd/utils/helpers/models.py

* Allow searches based on `build_model_filters` using `extra_columns` to do a string search. This really only applies to Admin Panel submission search

Allow string searching in extra_columns passed to build_model_filters

---

CTFd/api/v1/teams.py
CTFd/api/v1/users.py
CTFd/teams.py
CTFd/themes/core/templates/users/private.html
tests/api/v1/teams/test_scoring.py
tests/api/v1/users/test_scoring.py

There is some confusion with hidden/admins-only scoring. 
I want to clarify how we should view this type of scoring. 
* A user can see their on score even when it is hidden or admin. This is because a user can always calculate their own score by adding up all the challenges they have solved.
* Even under freeze time a user should still see their current score
* However place should be hidden under freeze time 
This updates the user & team personal profile pages and API endpoints to show an account's score even when score is hidden or admins only.

Clarify and update hidden score implementation

---

CTFd/utils/uploads/uploaders.py

The S3 Uploader is coded to assume that the system time will always be in UTC, this is not always going to be true.
fixes CTFd/CTFd#2431

bug: S3 uploader incorrect timezone

---

CTFd/api/v1/unlocks.py

* When unlocking a hint, always use an accounts true score and not their publicly visible score

When unlocking a hint, always use an accounts true score and not their public visible score

---

CTFd/utils/uploads/__init__.py

Fixes #2456
Issue was that boto3 `upload_fileobj` function closes the file object it is passed, so by moving hash calculation (which requires a reference to the file object) before the upload, the bug is fixed.

Fix S3 file upload

---

CTFd/utils/csv/__init__.py
tests/admin/test_csv.py

Allow challenge CSV to contain JSON in the hints and flags columns so that users can insert more complex data that includes commas. 
* Closes #2038 
* Closes #2395
Here is an example CSV:
```
name,category,description,value,flags,tags,hints
challenge1,category1,description1,100,"[{""type"": ""static"", ""content"": ""flag1"", ""data"": ""case_insensitive""}, {""type"": ""regex"", ""content"": ""(.*)"", ""data"": ""case_insensitive""}, {""type"": ""static"", ""content"": ""flag3""}]","tag1,tag2,tag3","[{""content"": ""hint1"", ""cost"": 10}, {""content"": ""hint2"", ""cost"": 20}, {""content"": ""hint3"", ""cost"": 30}]
```

Allow hints and flags to contain JSON to allow for better data control

---

CTFd/api/v1/teams.py

* Prevent teams with null passwords from generating invite codes until they set a password

Prevent teams with null passwords from generating invite codes until they set a password

---

CTFd/constants/assets.py

When creating custom templates, it can be useful to include some JavaScript code without `defer`. For example, in the case of a Bootstrap template this is needed to load a dark mode selector before showing the page (to prevent white/dark flickering).
Currently the only solution to remove defer is:
```diff
-  {{ Assets.js("assets/js/color_mode_switcher.js") }}
+  <script src="{{ Assets.file("assets/js/color_mode_switcher.js") }}"></script>
```
This pull request proposes to add an optional parameter "defer" to `Assets.js` to be able to write:
```diff
-  {{ Assets.js("assets/js/color_mode_switcher.js") }}
+  {{ Assets.js("assets/js/color_mode_switcher.js", defer=False) }}
```

Assets.js: add optional defer option

---

CTFd/api/v1/scoreboard.py
tests/users/test_scoreboard.py

Linked to issue https://github.com/CTFd/CTFd/issues/2493
When using CTFd API, I would expect `ScoreboardDetail` to return more information than `ScoreboardList`. JavaScript codes need to query twice the API then merge information.
This patch proposes to expose more fields for each standing in `ScoreboardDetail`.
*Note: renaming `id` to `account_id` would be nice, but it would break backward compatibility, so I'm not proposing that.*

Return more fields in ScoreboardDetail

---

CTFd/api/v1/scoreboard.py
CTFd/cache/__init__.py
CTFd/utils/scores/__init__.py
tests/api/v1/test_scoreboard.py
tests/users/test_scoreboard.py

Linked to issue https://github.com/CTFd/CTFd/issues/2493
This patch proposes to add an extra GET parameter in ScoreboardDetail to filter by bracket.
This is useful to create custom scoreboards in downstream CTFd themes.
**I need help with `@cache.cached(timeout=60, key_prefix=make_cache_key, query_string=True)`.** It seems that CTFd custom cache keys does not support `query_string` option.

Add bracker filter in ScoreboardDetail

---

CTFd/plugins/__init__.py
CTFd/views.py

* Return a proper Cache-Control header with an hour timeout instead of relying on the conditional browser checks

Improve caching by returning proper Cache-Control header for static file handlers

---

CTFd/utils/dates/__init__.py
tests/utils/test_ctftime.py

Add additional layer of None-checks to the time filter functions, to prevent 500s. Although we already covered the bug, it's possible we missed some edge cases, so I am fixing it closer to the source of the error

Add none-check to time filter funcs

---

CTFd/api/v1/teams.py
CTFd/models/__init__.py

* Allow teams with null passwords to create invite codes without setting their team password
This loosens the fix implemented in https://github.com/CTFd/CTFd/pull/2485. Teams with NULL passwords can now generate invite codes that are signed with only the CTFd secret key. 
The original idea was to use both the secret key and team password to allow revocation of the invite by changing the password but this achieves the same effect as if the team sets a password, the invite generated with only the secret key will no longer work

Allow teams with null passwords to create invite codes without setting their team password

---

CHANGELOG.md
CTFd/__init__.py

- The styling of the Config Panel has been updated to better organize different settings
- When switching user modes via the Admin Panel, all teams will now be removed
- Fix issues where importing CSVs comprised of JSON entries would fail
- Add `serializeJSON` function back into the Admin Panel
**API**
- The `/api/v1/exports/raw` API endpoint has been added to allow for exports to be generated via the API
- Update the ScoreboardDetail endpoint (`/api/v1/scoreboard/top/<count>`) to return account URL, score, and bracket
- Add a query parameter to ScoreboardDetail endpoint (`/api/v1/scoreboard/top/<count>`) to filter by bracket
- Return `function` field for DynamicValue challenges data read
**General**
- Add Italian and Vietnamese languages
- Switch to Crowdin for …

Mark 3.7.1

---

CTFd/constants/assets.py
CTFd/themes/admin/templates/challenges/preview.html

* Add `Assets.manifest(_return_none_on_load_failure=False)` to allow the Admin Panel to detect if the current theme is a legacy theme or modern theme
* Fix challenge preview for custom themes

Improve the way that the Admin Panel detects modern themes and fallbacks the challenge preview behavior

---

CTFd/admin/submissions.py
CTFd/admin/teams.py
CTFd/admin/users.py
CTFd/api/v1/comments.py
CTFd/api/v1/submissions.py
CTFd/api/v1/teams.py
CTFd/api/v1/users.py
CTFd/teams.py
CTFd/users.py

* Disable returning 404s in listing pages with pagination
* For the API endpoints instead of returning 404 these will now return 200 with an empty listing which is the better (and intended) response

Remove unexpected Flask-Sqlalchemy paginate 404

---

CTFd/utils/user/__init__.py

`get_current_user_attrs` can and will return `None` and needs to be handled appropriately by the functions that rely on it. Some already had `None` checkers, some did not.

Safer handling of None from get_current_user_attrs

---

docker-compose.yml

Remove warning from `docker compose`
```log
WARN[0000] docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion
```

Remove warning

---

CTFd/constants/assets.py

See https://github.com/CTFd/core-beta/pull/88 for discussion.
My bad, I didn't know that `type="module"` on a `<script>` tag implies defer mode.

assets.py: JS as module implies defer

---

requirements.in
requirements.txt

* Bump requests to 2.32.3
* Bump boto3 to 1.35.27
This starts work on getting CTFd to run on Python 3.12

Bump dependencies for 3.12

---

CHANGELOG.md
CTFd/__init__.py

**Security**
- Validate email length to be less than 320 chars to prevent Denial of Service in email validation
**General**
- Add attribution field to Challenges
- Display brackets in the Admin Panel
**Themes**
- Display brackets for users/teams on listing pages and public/private pages
- Fix miscellaneous issues in core-beta
- Adds dark mode to core-beta theme
- Fix issue with long titles in challenge buttons
- Adds `type` and `extra` arguments to `Assets.js()` and default `defer` to `False` as `type="module"` automatically implies defer
- ECharts behavior for some graphs in core-beta can now be overriden using the following window objects `window.scoreboardChartOptions`, `window.teamScoreGraphChartOptions`, `window.userScoreGraphChartOptions`
- Update the scoreboard …

Mark 3.7.4

---

CTFd/utils/initialization/__init__.py
CTFd/utils/user/__init__.py

Before each request, the initialization process module executes the following process:
1. Query the cache to get the recent IPs of the current user
- If the cache is missing, select the recent IPs from the database.
- The comparison is computed using `datetime.datetime.now() - datetime.timedelta()` 
- The MySQL query isn't timezone aware, the date will be encoded in local time without timezone information
2. If the request IP isn't stored in database OR if the request is not GET then update the database
- The date column is filled using `datetime.datetime.utcnow()`
- The cache is invalidated
The first bug is caused by the following condition:
```python
if (ip not in user_ips) or (request.method != "GET"):
```
Browser issue many HEAD requests and trigger this condition. This invalidates …

Tracking: Fix "cache miss" bug which causes too many DB queries

---

CTFd/utils/initialization/__init__.py
CTFd/utils/user/__init__.py

@adam-lebon I am reverting the datetime changes here because I think it will be better to put it in an whole application wide migration
Also using utcnow in the recent IPs query to fix the issue you had raised

Revert datetime changes from #2653

---

CTFd/auth.py
CTFd/exceptions/email.py
CTFd/utils/email/__init__.py
CTFd/utils/security/email.py
tests/users/test_auth.py
tests/utils/test_email.py

* Convert confirmation & reset password emails to single use by storing the email tokens in caching

Convert confirmation & reset password emails to single use

---

CTFd/__init__.py
CTFd/config.ini
CTFd/config.py
tests/test_config.py

* Backport the `TRUSTED_HOSTS` config setting from Flask 3.1

Backport TRUSTED_HOSTS from Flask 3.1

---

CHANGELOG.md
CTFd/__init__.py

**Security**
- Added the `TRUSTED_HOSTS` configuration to more easily restrict CTFd to valid host names
**General**
- Added language switcher on the main navigation bar
- Removed autocomplete=off from login, register, and reset password forms
**Plugins**
- Challenge type plugins can now raise `ChallengeCreateException` or `ChallengeUpdateException` to show input validation messages
- Plugins specifying a config route will now appear in the Admin Panel under the Plugins section
**Translations**
- Add Romanian, Greek, Finnish, Slovenian, Swedish languages

Mark 3.7.6

---

CTFd/api/v1/hints.py
tests/api/v1/test_hints.py

* Fix issue where admins would automatically be able to see hints without unlocking or meeting prerequisites
* Admins should primary see hints in the Admin Panel challenge preview window but can also use `?preview=true` when requesting to view the hint

Fix issue where admins would automatically be able to see hints without unlocking or meeting prerequisites

---

CTFd/auth.py
CTFd/forms/auth.py
CTFd/views.py
tests/users/test_auth.py
tests/utils/test_email.py

* Email confirmation is now enabled if email sending is enabled on the CTFd instance
* CTFd will also nudge users to verify their email with a dismissable message

Make email verification a default feature if email sending is enabled

---

CTFd/auth.py
CTFd/config.ini
CTFd/config.py

* Closes #2690
* Adds `EMAIL_CONFIRMATION_REQUIRE_INTERACTION` to config.ini and config.py which controls whether confirmation links confirm accounts upon opening the confirmation link or if it confirms upon clicking an additional button.

Add the ability to require browser interaction on email confirmation links

---

CTFd/api/v1/shares.py
CTFd/constants/config.py
CTFd/forms/config.py
CTFd/forms/setup.py
CTFd/share.py
CTFd/themes/admin/templates/configs/social.html
CTFd/utils/social/__init__.py
CTFd/views.py
tests/test_share.py

* Allow admins to control the template that is shown when users click share links
* Enable social shares by default
* Closes #2802

Allow admins to control the share template

---

CTFd/__init__.py
CTFd/config.ini
CTFd/config.py

Allow deployments to specify a `RUN_ID` environment variable so that all workers will use the same run_id for cache busting (see #2681).
Logic is:
- If in debug mode, use prior behavior run_id (time-based)
- Otherwise, if RUN_ID environment variable is set, use that, otherwise fall back to time-based.
Should be backward compatible but allow deployments to specify a RUN_ID.

feat: Allow deployment to specify RUN_ID environment variable 
