CTFd/__init__.py
CTFd/admin.py
CTFd/auth.py
CTFd/challenges.py
CTFd/scoreboard.py
CTFd/utils.py
CTFd/views.py
requirements.txt

I started to cleanup the code because I'm planning to use it for an upcoming workshop. Great work btw, thanks for putting this on GitHub! :)
During the cleanup I stumbled across some missing imports, syntax errors and uncaught exceptions. This commit fixes some of them. Especially the imports look pretty messed up. Most notably, Flask functions should not be imported via the `CTFd` module but directly from `flask`.
Resolving these and some other import issues might allow you to not put every module's code in a pseudo-function where other modules won't be able to import global instances (like `mail`). :)

Missing dependencies added, some weird imports fixed

---

CTFd/admin.py

there is a ban/uban switcher in admin/exoreboard.html, but when you query the database, you lost the parameter.

make the ban and unban switcher work

---

prepare.sh
requirements.txt

Install libffi-dev in prepare.sh. Bcrypt seems to depend on this.
Add exact versions for all packages in requrements.txt

Update installation scripts

---

CTFd/admin.py
templates/admin/pages.html

This should resolve Issue #32,
Admins have the ability to delete pages.

Admins can delete pages

---

CTFd/admin.py
CTFd/challenges.py
CTFd/utils.py
templates/admin/config.html
templates/chals.html

Trying this again.
Fixes issue #29

View challs after

---

CTFd/admin.py
CTFd/challenges.py
CTFd/models.py
templates/admin/correct_keys.html
templates/admin/statistics.html
templates/admin/wrong_keys.html

fixes #37  (interface to view incorrect submissions)
also interface to view correct submissions, does not have capability to delete correct submissions yet.
EDIT: now has the ability to delete previously submitted keys. issue #36 
NOTE: because of the schema change to solves, this does not work with current ctfd.db files.

view incorrect/correct key submission interfaces

---

prepare.sh

Removes the need for user input during server setup

Fully automate prepare.sh

---

CTFd/templates/setup.html

Found the culprit to my previous PR #56

change setup template text to use new /login url instead of /admin login

---

CTFd/challenges.py

fix for lowercase comparison bug

---

CTFd/templates/admin/login.html

Solve the admin login page csrf problem caused by the lack of nonce

Add nonce element in admin/login.html

---

CTFd/static/js/scoreboard.js

Don't know if this is your original idea

Fixed scoreboard show graph bug

---

CTFd/admin.py
CTFd/challenges.py
CTFd/models.py
CTFd/scoreboard.py

Added defaults to db.Boolean columns and changed comparisons from `==None` to `==False`.

Add defaults to boolean columns in the Team model

---

CTFd/static/original/admin/js/team.js

Fix issue reported in #138.

---

CTFd/templates/admin/config.html

Added side nav pills to config page

---

CTFd/challenges.py
CTFd/static/original/js/chalboard.js

Changed the /chals/colves endpoint and associated javascript to
index solves by challenge id rather than by challenge name
Closes (#169)

Reference solves by id (#169)

---

CTFd/__init__.py
CTFd/admin.py
CTFd/auth.py
CTFd/challenges.py
CTFd/config.py
CTFd/models.py
CTFd/plugins/__init__.py
CTFd/scoreboard.py
CTFd/templates/admin/base.html
CTFd/templates/admin/editor.html
CTFd/templates/admin/pages.html
CTFd/utils.py
CTFd/views.py
populate.py
serve.py
tests/helpers.py
tests/test_ctfd.py
tests/test_user_facing.py
wsgi.py

PEP 8 Complicate from arthaud, some more tests and some cleaning up with Pages. 
Completely changes config.py to have a Config class which can be inherited against and used to create custom CTFd instances with different values. Big change but gives us lots of flexibility. 
Markdown was tested and is very simplistic to add but not as streamlined as possible yet so not added in.

Latest set of changes

---

CTFd/admin.py
CTFd/challenges.py
CTFd/scoreboard.py
CTFd/views.py

This is basically to prevent errors 500 (for instance, when visiting /teams/1xxxx, /team/1xxx or /admin/team/1xxx)

Use <int:xxx> in routes to prevent some errors 500

---

CTFd/admin.py
CTFd/auth.py
CTFd/challenges.py
CTFd/views.py

This fixes some other errors that can be triggered by using invalid IDs in URLs.

Use first_or_404() to prevent some errors 500

---

CTFd/admin/challenges.py
CTFd/config.py
CTFd/utils.py
CTFd/views.py

Fixed hard coded upload directory

---

CTFd/admin/__init__.py
CTFd/challenges.py
CTFd/scoreboard.py
CTFd/static/admin/js/utils.js
CTFd/static/original/js/templates/challenges/standard/standard-challenge-modal.hbs
CTFd/static/original/js/utils.js
CTFd/templates/admin/config.html
CTFd/templates/original/base.html
CTFd/templates/original/scoreboard.html
CTFd/templates/original/team.html
CTFd/templates/original/teams.html
CTFd/utils.py
CTFd/views.py

Adds hiding scores functionality

Hide scores

---

.travis.yml
README.md

Next steps:
* Go to https://travis-ci.org/
* Click "Sign in with GitHub"
* Click your user icon and click "Accounts"
* Enable for CTFd

Added CI integration with Travis-CI

---

CTFd/__init__.py
CTFd/admin/__init__.py
CTFd/admin/challenges.py
CTFd/admin/containers.py
CTFd/admin/keys.py
CTFd/admin/pages.py
CTFd/admin/scoreboard.py
CTFd/admin/statistics.py
CTFd/admin/teams.py
CTFd/auth.py
CTFd/challenges.py
CTFd/scoreboard.py
CTFd/templates/admin/teams.html
CTFd/views.py
tests/helpers.py
tests/test_admin_facing.py
tests/test_user_facing.py

Adds some weak tests for the admin facing side. Most importantly changes utils to be called as `utils.get_ip()` instead of `get_ip()`. This means that most util functions can be monkey patched with a plugin.

Plugins enhanced utils

---

CTFd/admin/challenges.py
CTFd/utils.py

delete_file util to complement the upload_file util. Should make the s3 plugin much simpler.

Adds delete_file util

---

CTFd/admin/challenges.py
CTFd/utils.py

Fixes challenge deletion with the new delete_file util

Fix chal deletion

---

README.md

+ legibility
+ ability to link to section anchors directly

Use headlines in README

---

docker-entrypoint.sh

I think ultimately each container can be parallelized so this shouldn’t
be a huge issue.

Remove --threads

---

CTFd/models.py
tests/test_utils.py

Give ip2long and long2ip ipv6 support

---

CTFd/admin/teams.py
CTFd/templates/admin/teams.html

This adds team searching capabilities for the admin panel. Not a very advanced search, but it works for the purposes of most. 
Perhaps this will be expanded to IP search as well.

Admin panel team search

---

CTFd/admin/__init__.py
CTFd/templates/admin/base.html

Potentially opens up the config page to ACE but really any plugin would have that capability.

Giving config page more access

---

CTFd/challenges.py

Fixing hints glitches

---

CTFd/utils.py

Rearranging some imports

---

CTFd/themes/original/static/js/scoreboard.js
CTFd/themes/original/static/js/team.js

Making user facing graphs transparent

---

CTFd/__init__.py
CTFd/utils.py
tests/test_utils.py

Purely for use by plugins to replace templates in an existing theme

Adding override_template function

---

CTFd/auth.py
CTFd/themes/original/templates/confirm.html
tests/test_utils.py

Send confirmation emails on register and add button to resend email

---

tests/test_utils.py

This adds a test for the SMTP version of the CTFd sendmail wrapping function.

Adding SMTP sendmail unit test

---

CTFd/__init__.py

Marking 1.0.3

---

CTFd/config.py

It would be helpful to have the option to set the UPLOAD_FOLDER via environment variable. This change allows that.

Environment var for UPLOAD_FOLDER

---

CTFd/models.py

fix inconsistent scoring: take awards into account in user.place()

---

CTFd/models.py
tests/helpers.py
tests/test_user_facing.py

Adding tests for @rkkautsar's scoring logic changes

Fixing scoring logic

---

CTFd/auth.py

Adds more logging to auth.py

---

CTFd/themes/original/static/js/multi-modal.js

Thanks again to @nategraf for fixing the `multi-modal.js` file.

Copy multi-modal.js from the admin panel

---

CTFd/admin/__init__.py
CTFd/themes/admin/templates/config.html
CTFd/utils.py
CTFd/views.py

Here is a more elegant (complex) solution to 339 & 340. Still missing here is error handling with feedback for the exception cases. 
Added a toggle to the config page and updated all the obviously relevant areas to reflect the new config option.

Fixing smtp combine fix 339 and 340 more complete

---

CTFd/auth.py
CTFd/config.py
CTFd/utils.py
tests/test_utils.py

Using a Python 3 compatible base64 encoder and fixing verify_emails

---

CTFd/auth.py
CTFd/themes/original/templates/confirm.html
CTFd/utils.py
tests/test_utils.py

Recent changes broke both of these in the name of fixing other errors.

Fixing email confirmation and adding more base64 tests

---

CTFd/themes/original/static/js/templates/challenges/standard/standard-challenge-modal.hbs
CTFd/themes/original/static/js/templates/challenges/standard/standard-challenge-script.js

This closes #342 but at the cost of being a very odd solution. That being said, challenge types have been implemented very strangely and I'm open to all suggestions on how to improve it.

Render descriptions encoded, and then decode and render with marked

---

CTFd/admin/challenges.py

Hints should default to a 0 cost if no cost is specified.

Making hints cost 0 by default

---

.gitignore
Vagrantfile
prepare.sh
scripts/install_docker_ubuntu.sh

* Add Vagrantfile for development with an Ubuntu base box
* Add Docker support to Vagrant VM
Closes #284

Add Vagrant with docker support (#285)

---

CTFd/auth.py

Seems like I was missing getting a logger in reset_password. Need to write a test around this as well.

Fixing reset password logger

---

requirements.txt

Adding redis to requirements just in case it isn't installed before

Adding redis to requirements

---

tests/test_utils.py

Issue #362 says this is a problem but not sure if that's really the case or not. Regardless add some tests because it is a valid scenario.

Adding test for encoding emails with plus signs

---

CTFd/utils.py

I'm not even really sure this is a bug to be honest. If you clear out the database, you should also clear your cookies. 
Fundamentally the flaw in #367 is that when you clear the database, the cookie in your browser will still point to a Team id that does not exist. Then attempting to track on a user that doesn't exist will cause SQLAlchemy to complain. 
I think overall the code doesn't get any worse so it should be fine but the tracker code is called very often and I don't want to add any complexity or lag there.

Handle when database is cleared

---

CTFd/themes/original/templates/base.html
CTFd/utils.py
tests/test_utils.py

Adds the ability for plugins to register CSS files so that they can change aesthetics.

Plugins can register css files

---

CTFd/scoreboard.py
CTFd/themes/original/static/js/scoreboard.js
tests/helpers.py
tests/user/test_scoreboard.py

An anonymizing plugin revealed an issue where `/top/10` doesn't work properly if users share names. Since this could reasonably happen in a more production instance it bears fixing.

Top ten endpoint honors users with the same name

---

CTFd/challenges.py
tests/user/test_challenges.py

Adds test for `/chals/solves`
Closes #326

Cleaning some challenge endpoints

---

CTFd/themes/admin/static/css/style.css
CTFd/themes/admin/static/js/team.js
CTFd/themes/admin/templates/graphs.html
CTFd/themes/admin/templates/team.html
CTFd/themes/original/static/css/style.css
CTFd/themes/original/static/js/chalboard.js
CTFd/themes/original/static/js/scoreboard.js
CTFd/themes/original/static/js/team.js
CTFd/themes/original/templates/chals.html
CTFd/themes/original/templates/scoreboard.html
CTFd/themes/original/templates/team.html

Add spinners so that there's not just a giant block of empty space when we generate a graph.

Adding spinners to the scoregraph load and chalboard

---

CTFd/themes/original/static/js/chalboard.js

Accidentally messed up challenge ordering (from lowest points to highest).

Fixing challenge ordering bug introduced

---

CTFd/challenges.py
tests/test_utils.py
tests/user/test_challenges.py

Add tests for seeing challenges while unregistered and also revert some changes to some of the challenge APIs.

Fixing issues with loading /chals when unregistered

---

CTFd/utils.py

Revert change to utils.py for now because of difficulty with accessing utilities. Need a better solution and #357 can in theory already be done.

Reorder get config access

---

CTFd/challenges.py
CTFd/plugins/challenges/__init__.py
CTFd/utils.py
tests/user/test_challenges.py

Expands challenge type plugins to have a solve and fail method which dictates how the plugin should deal with correct/incorrect solutions.

Improve Challenge type plugin staticmethods

---

CTFd/themes/admin/static/css/style.css
CTFd/themes/admin/templates/base.html
CTFd/themes/admin/templates/team.html
CTFd/themes/original/static/css/style.css
CTFd/themes/original/static/js/scoreboard.js
CTFd/themes/original/static/js/team.js
CTFd/themes/original/templates/scoreboard.html
CTFd/themes/original/templates/team.html

Closes #390 
Push the admin footer to the bottom properly in the admin panel. 
Fix up a few formatting issues in JS.

Remove spinners if there is no data, push footer down to the bottom

---

CTFd/plugins/__init__.py
tests/helpers.py
tests/test_plugin_utils.py

Adds functions to make it easier for plugins to register assets.

Adding functions to register plugin assets

---

CTFd/plugins/challenges/assets/standard-challenge-modal.hbs
CTFd/themes/admin/templates/base.html
CTFd/themes/admin/templates/config.html
CTFd/themes/admin/templates/correct_keys.html
CTFd/themes/admin/templates/editor.html
CTFd/themes/admin/templates/pages.html
CTFd/themes/admin/templates/scoreboard.html
CTFd/themes/admin/templates/statistics.html
CTFd/themes/admin/templates/teams.html
CTFd/themes/admin/templates/wrong_keys.html
CTFd/themes/original/static/js/chalboard.js

Closes #400 
Cleans up admin panel slightly

Fixing subdirectory deployment

---

CTFd/challenges.py
tests/user/test_challenges.py

Anti-bruteforce failures didn't use the challenge type plugin's fail method so this fixes that and adds some tests.

Pass all failure attempts to the challenge plugin

---

CTFd/challenges.py

Noticed that hiding scores meant that a user couldn't see their own graphs.

Fixing users being able to see their own graphs when scores are hidden

---

CTFd/themes/original/static/js/team.js
CTFd/themes/original/templates/team.html
CTFd/views.py
tests/user/test_user_facing.py

Creates a private team endpoint that doesn't disclose IDs

Create a private team endpoint

---

migrations/versions/e62fd69bd417_use_strings_for_key_types.py

Fixes the latest migration script for upgrading.

Fixing migration script for upgrade

---

CTFd/admin/__init__.py
CTFd/plugins/__init__.py
CTFd/themes/admin/templates/base.html
CTFd/themes/original/templates/base.html
CTFd/utils.py
tests/test_plugin_utils.py

This gives plugins the ability to add links (external or internal) to the user navbar and also add internal links to the Admin Panel as part of a plugin menu. 
Closes #423

Navbar links

---

CTFd/admin/__init__.py
CTFd/themes/admin/templates/config.html

Remove the currently set configuration if the checkbox is unchecked
Closes #422

Don't render the mail server password

---

CHANGELOG.md
CTFd/__init__.py

Gets ready to tag a 1.0.5 release.

Adding 1.0.5 changes

---

CTFd/admin/pages.py
CTFd/themes/admin/templates/editor.html
CTFd/themes/admin/templates/pages.html
CTFd/views.py
tests/admin/test_pages.py

Closes #449
Pages can now have slashes in them as long as they are not leading.

Allowing pages to have slashes in them but removing leading slashes

---

tests/admin/test_admin_facing.py

Fixing challenge creation test

---

CTFd/scoreboard.py

Closes #453 
Instead of making a database call every iteration of the for loop, just make the needed database calls once and then organize it into the right structure after we have everything.

Optimize top10 call to make less db hits

---

.travis.yml
CTFd/admin/__init__.py
CTFd/challenges.py
CTFd/themes/admin/templates/config.html
CTFd/themes/original/static/css/style.css
CTFd/themes/original/templates/base.html
CTFd/utils.py
CTFd/views.py
tests/user/test_challenges.py
tests/user/test_user_facing.py

Create a config to allow people to hide teams and scores. To be used for recruiting events or class homework.

Workshop mode

---

Vagrantfile

This appears to be working from my local testing. 
Closes #466

Switching to Bento Ubuntu for VMWare support

---

CTFd/utils.py
CTFd/views.py
tests/user/test_user_facing.py

Profile insertion check

---

CTFd/themes/admin/static/js/hints/hints-utils.js
CTFd/themes/admin/templates/modals/hints/hints.html

Closes #444
Hints have a preview now for creating and updating hints. HTML and markdown are still allowed.

Adding a basic preview to hints

---

CTFd/themes/bootstrapv4/static/js/chalboard.js

Closes #479
This modifies the loadchals JS function to not be concerned with marking challenges as solved. Instead this is passed off to load_user_solves. 
Now the order of loading data from CTFd is as follows:
1. Load user solves
2. Load challenges (and mark them as solved based on Step 1)
3. Load challenge solve counts
4. Load the challenge that's specified by the location hash

Update load chals

---

.travis.yml
development.txt

Closes #501. 
Installs codecov
Looks great: https://codecov.io/gh/CTFd/CTFd

Adding codecov

---

CTFd/admin/teams.py
CTFd/themes/admin/templates/teams.html
CTFd/utils.py

Closes #346
Improves error handling in sendmail so that it returns a result and a message.

Sendmail improvements

---

requirements.txt

Adding Flask-Script

---

CTFd/challenges.py
CTFd/themes/bootstrapv4/templates/challenges.html
tests/user/test_challenges.py

Make sure that users can still see challenges when the CTF is paused.

Fix loading challenges for users

---

CTFd/themes/admin/templates/config.html

Signed-off-by: David Black <dblack@atlassian.com>

When css is not set default it to an empty string instead of showing None

---

CTFd/utils.py

Signed-off-by: David Black <dblack@atlassian.com>

To allow previous version imports of keys to work - fill in key `type` from `key_type`.

---

CTFd/themes/admin/static/js/challenges/chalboard.js
CTFd/themes/admin/templates/correct_keys.html
CTFd/themes/admin/templates/team.html
CTFd/themes/admin/templates/teams.html
CTFd/themes/admin/templates/wrong_keys.html
CTFd/themes/core/static/css/base.css
CTFd/themes/core/static/js/chalboard.js

Closes #527 
Adds a callback to `submitkey()`
Deleting submissions no longer causes a page refresh

Adding a cb to submitkey, delete submissions & don't reload & close #527

---

CTFd/utils.py
tests/test_utils.py

Prioritize mailserver over mailgun and test mailgun behavior.

Use mailserver before mailgun & test mailgun behavior

---

CTFd/__init__.py
CTFd/utils.py
tests/test_themes.py

Themes are now inside of the Jinja [SandboxEnvironment](http://jinja.pocoo.org/docs/2.10/sandbox/)
`get_config()` can no longer access app.config values.
`get_app_config()` is now used for that purpose if you don't want to just access them directly with `app.config`

Sandbox themes

---

CTFd/plugins/challenges/assets/standard-challenge-update.njk

Fix challenge updating on subdirectory deployments

---

CTFd/themes/core/templates/base.html

Fixing issue with linking to pages in subdirectory deployments

---

CHANGELOG.md
CTFd/__init__.py

**General**
* Fixed page links on subdirectory deployments
* Fixed challenge updating on subdirectory deployments
* Fixed broken icon buttons on Safari
**Themes**
* Upgraded to Bootstrap 4.0.0
* Upgraded to jQuery 3.3.1
* Upgraded to FontAwesome 5.0.4

Marking 1.1.2

---

CTFd/plugins/challenges/assets/standard-challenge-update.js
CTFd/plugins/challenges/assets/standard-challenge-update.njk
CTFd/themes/admin/static/js/challenges/chalboard.js
CTFd/themes/admin/templates/challenges.html

* Switch update modals to use nunjucks instead of JS to load in data. 
* Fix previewing challenges after hitting the challenge update button.
* Fix edit-files issue with an unnecessary request.

Update modal change

---

CTFd/themes/admin/static/js/keys/keys-utils.js

Reset flag modal when the modal is loaded

---

CTFd/__init__.py
CTFd/utils.py

Force update checks on startup

---

CTFd/views.py

Remove static_html template code

---

CTFd/plugins/challenges/__init__.py
tests/admin/test_admin_facing.py

Fixes a bug where challenges with hints could not be deleted.

Fix deleting chals when they have a hint

---

CHANGELOG.md
CTFd/__init__.py

**General**
* [SECURITY] Fixed XSS in team website. (#604)
* Fixed deleting challenges that have a hint associated. (#601)

Marking 1.1.4

---

CTFd/themes/admin/static/js/ezq.js
CTFd/themes/admin/static/js/utils.js
CTFd/themes/core/static/js/ezq.js
CTFd/themes/core/static/js/utils.js

This adds a progressbar wrapper to ezq. Also adds a PATCH method utility for AJAX.

Add ezpg and jquery PATCH wrapper

---

CTFd/utils.py

Thanks to @josconno for reporting this issue!

Fix imports issue

---

CTFd/utils.py

Fixes issue importing null objects

---

CTFd/themes/core/templates/teams.html

Truncating team names properly when scores arent hidden

---

docker-entrypoint.sh

Potential but likely fixes for https://github.com/CTFd/CTFd/issues/637. 
Closes #637

Initialize database in docker-entrypoint.sh to reduce likelihood of missing tables

---

Vagrantfile

Makes Vagrant use a maria database rather than sqlite (which wasn't working as it was).

Vagrant uses mariadb database rather than sqlite - Fixes #648

---

CTFd/themes/admin/static/js/team.js
CTFd/themes/admin/templates/statistics.html
CTFd/themes/core/static/js/scoreboard.js
CTFd/themes/core/static/js/team.js

Fixes https://github.com/CTFd/CTFd/issues/682 .

Change default filename for PNG export

---

CTFd/admin/__init__.py
CTFd/admin/teams.py
CTFd/admin/users.py
CTFd/auth.py
CTFd/challenges.py
CTFd/teams.py
CTFd/themes/admin/templates/config.html
CTFd/themes/admin/templates/configs/mlc.html
CTFd/utils/helpers/__init__.py
tests/users/test_hints.py

* Create and use new wrappers to flash messages (errors, infos)
* Create and use new wrappers to get flashed messages

Auth Improvments

---

CHANGELOG.md
CTFd/config.py

Finalize 2.0.0

---

CHANGELOG.md
CTFd/plugins/dynamic_challenges/__init__.py
CTFd/themes/admin/templates/configs/settings.html
CTFd/utils/updates/__init__.py
README.md
migrations/1_2_0_upgrade_2_0_0.py
tests/challenges/test_dynamic.py
tests/helpers.py

* Upgrade migration script to port visibility settings
* Add message about visibility settings conflicts between score visibility and account visibility 
* Port over visibility settings during initial 1.2.0 -> 2.0.0 migration

Mark 2.0.0

---

CTFd/plugins/dynamic_challenges/__init__.py
CTFd/themes/core/templates/teams/team_enrollment.html
tests/challenges/test_dynamic.py

* Fix dynamic challenges to work in user mode and team mode (Closes #759)
* Add test for solving dynamic challenges and challenge de-valuation

Fix dynamic challenges to work in user mode and team mode

---

CTFd/themes/core/templates/users/user.html

* Fix /user page for users without teams (e.g. user mode)

Fix user.html when running in user mode without a team

---

docker-compose.yml

* Update mariadb to 10.4
* Remove `LOG_FOLDER` from docker-compose.yml

Update mariadb to 10.4 based on #726

---

CTFd/admin/challenges.py
tests/admin/test_challenges.py

* Fix `update.html` in Python 3

Fix issue loading update view in Python 3. Thanks to @mayoneko

---

CTFd/utils/exports/__init__.py
tests/utils/test_exports.py

* Use tempfile.SpooledTemporaryFile() instead of raw BytesIO

Use tempfile.SpooledTemporaryFile() instead of raw BytesIO

---

CTFd/auth.py
CTFd/models/__init__.py
CTFd/schemas/teams.py
CTFd/schemas/users.py
CTFd/themes/admin/templates/configs/accounts.html
CTFd/views.py
tests/api/v1/test_teams.py
tests/api/v1/test_users.py
tests/test_themes.py
tests/users/test_auth.py

* Fix creating users & teams from the API
* Hash user/team password in the model vs the schema
* Stop caching CSS at the decorator level
* Fix tests

Fix creating users, teams from the API

---

CTFd/themes/core/static/js/challenges.js
CTFd/themes/core/templates/challenges.html
CTFd/themes/core/templates/users/users.html

* Only call load_user_solves if authed to avoid a 403
* Fix user.html page links

Only call load_user_solves if authed

---

CTFd/__init__.py
CTFd/config.py
CTFd/utils/events/__init__.py

* Allow setting SocketIO async mode from envvar or config.py

Allow setting SocketIO async mode from envvar or config.py

---

CTFd/admin/__init__.py
tests/admin/test_config.py
tests/helpers.py

* Expand tests for CTFd resets and fix issues identified
* Fix helpers for fails, tracking

Fix resets in mysql

---

CTFd/utils/uploads/uploaders.py

* Fix S3 sync function to only pull down files

Fix S3 sync function to only sync down full files

---

CTFd/api/v1/challenges.py
CTFd/views.py
tests/users/test_views.py

* Fix downloading files as an anonymous user. 
* Fix viewing challenges anonymously if they have empty requirements or are anonymized.
* Closes #789

Fix downloading files as an anonymous user. 

---

CTFd/auth.py
CTFd/themes/admin/templates/configs/email.html
CTFd/themes/core/templates/confirm.html
tests/users/test_auth.py

* Fix email confirmations and improve test. 
* Breaks confirm.html page because of change from team to user
* Clean up admin mail settings to use new label/small structure
* Fix password resets from double hashing passwords

Fix email confirmations and password resets

---

CTFd/plugins/__init__.py
CTFd/themes/admin/templates/base.html
CTFd/utils/initialization/__init__.py
CTFd/utils/plugins/__init__.py
tests/test_plugin_utils.py

* Adds plugin functions to register javascript and CSS in the admin panel
* Move global plugin script/stylesheet lists into application factory specific lists
* Closes #804

Adds plugin functions to register javascript and CSS in the admin panel

---

CTFd/plugins/dynamic_challenges/assets/update.html
CTFd/themes/admin/templates/base.html
CTFd/themes/core/templates/base.html

Fix wrong quotes for base.html

Update dynamic_challenges plugin ui to disable modification of current_value items

---

requirements.txt

Closes #816 
Pin version of normality to work around https://github.com/pudo/normality/issues/6.

Pin normality version

---

CTFd/admin/submissions.py
CTFd/admin/teams.py
CTFd/admin/users.py
CTFd/teams.py
CTFd/users.py

* Fix some 500s generated by invalid page arguments

Fix 500s from invalid page args

---

CTFd/themes/admin/templates/base.html
CTFd/themes/core/static/js/CTFd.js
CTFd/themes/core/templates/base.html
CTFd/themes/core/templates/challenges.html
CTFd/themes/core/templates/confirm.html
CTFd/themes/core/templates/notifications.html
CTFd/themes/core/templates/reset_password.html
CTFd/themes/core/templates/scoreboard.html
CTFd/themes/core/templates/settings.html
CTFd/themes/core/templates/setup.html
CTFd/themes/core/templates/teams/team.html
CTFd/themes/core/templates/teams/team_enrollment.html
CTFd/themes/core/templates/users/user.html
CTFd/utils/initialization/__init__.py
tests/api/v1/user/test_hints.py

* Simplify url_for calls in themes (Closes #784)
* Remove cruft from CTFd.js that we're not using.
* Fix a flaky test for hints

Simplify url_for calls in themes, rework CTFd.js, fix flaky test

---

CTFd/__init__.py
CTFd/utils/initialization/__init__.py
CTFd/utils/logging/__init__.py

* Closes #835 
* Move `utils.logging.init_logs()` into `utils.initialization`

Call init_logs() function to add logging handlers. 

---

CTFd/config.py
docker-entrypoint.sh
requirements.txt

* Install `gevent-websocket` and use it by default until we have a better solution
* May help with #849

Install gevent-websocket 

---

CTFd/challenges.py
tests/users/test_challenges.py

* Fix showing incorrect 'CTF has ended' error if `view_after_ctf` is set.

Fix showing incorrect 'CTF has ended' error if view_after_ctf is set

---

Dockerfile

* Adds `linux-headers` package to Dockerfile
* Closes #866

Closes #866

---

CTFd/utils/exports/__init__.py

* Replace `tempfile.SpooledTemporaryFile` with `tempfile.NamedTemporaryFile` in exports code

Replace tempfile.SpooledTemporaryFile with tempfile.NamedTemporaryFile

---

CTFd/utils/exports/__init__.py

* This closes #861 by forcing the database to recreate all tables (including those created by plugins)

Closes #861

---

.travis.yml
CTFd/auth.py
CTFd/utils/__init__.py
CTFd/utils/crypto/__init__.py
CTFd/utils/security/passwords.py
CTFd/utils/updates/__init__.py
tests/users/test_auth.py
tests/utils/test_passwords.py

* Move `CTFd.utils.security.passwords` into `CTFd.utils.crypto` 
* Closes #884

Move CTFd.utils.security.passwords into CTFd.utils.crypto (Closes #884)

---

CTFd/schemas/users.py
CTFd/themes/core/static/js/settings.js
CTFd/themes/core/templates/settings.html
CTFd/utils/validators/__init__.py
tests/users/test_settings.py
tests/users/test_views.py
tests/utils/test_validators.py

* Fix removing profile details from the settings page (Closes #894)

Fix removing profile details (Closes #894)

---

CTFd/models/__init__.py

This should be a straightforward change.

Fix Teams.get_solves query

---

CTFd/api/v1/users.py

* Fix incorrect UserSchema view use

Fix incorrect UserSchema view

---

CTFd/models/__init__.py

* Fix order_by clause in Teams.get_solves

Fix order by clause in Teams.get_solves

---

CTFd/api/v1/users.py
CTFd/themes/admin/static/js/users/actions.js
CTFd/themes/admin/templates/modals/mail/send.html
tests/api/v1/test_users.py

* Reimplement admin send mail to users as `/api/v1/users/<user_id>/email`
* Update form and related Javascript
* Write test for controller
* Closes #897

Reimplement admin send mail to users

---

Dockerfile
docker-entrypoint.sh
tests/utils/test_events.py

* Don't run as root inside of the Docker image. 
* Closes #720

Don't run as root in docker image

---

CTFd/api/v1/challenges.py
CTFd/themes/admin/templates/configs/settings.html
CTFd/utils/config/visibility.py
CTFd/utils/decorators/visibility.py
tests/admin/test_challenges.py
tests/users/test_challenges.py

* Adds an Admins Only option for Challenge Visibility
* Closes #806

Add an 'Admins Only' option for Challenge Visibility

---

CTFd/models/__init__.py
tests/users/test_scoreboard.py

* Users that are hidden shouldn't be factored into the calculation of place for other players. 
* Clean up a few other tests.

Dont calculate hidden users in place

---

CTFd/plugins/dynamic_challenges/__init__.py
tests/challenges/test_dynamic.py

* Record a new solve before calculating the new dynamic value.

Record a new solve before calculating the new dynamic value.

---

CHANGELOG.md
CTFd/__init__.py

* Bump version to 2.0.5
* Update CHANGELOG.md

Update CHANGELOG and bump version

---

CTFd/themes/admin/templates/base.html
CTFd/utils/events/__init__.py
docker-compose.yml
docker-entrypoint.sh
wsgi.py

* Improve SSE code to detect disconnected clients
* Use gevent to timeout blocking calls for new SSE
* Poll clients every ten seconds with a "ping" SSE
* Bump default `WORKERS` value to 4 in docker-compose and Dockerfile

Improve SSE code to detect disconnected clients

---

CTFd/themes/admin/templates/base.html
CTFd/themes/admin/templates/notifications.html
CTFd/themes/core/static/js/events.js
CTFd/themes/core/static/js/vendor/window-controller.js
CTFd/themes/core/templates/base.html

* Use localStorage to bypass the browser's connection limits
* Thanks to https://gist.github.com/neilj/4146038
* View notifications on all admin panel pages
* Closes #921

Use localStorage to bypass TCP connection limits in browsers for SSE

---

CTFd/themes/admin/static/js/pages/editor.js
CTFd/themes/admin/templates/editor.html

* Adds UI to delete and download files from the media library
* Closes #860

860 delete media files ui

---

CTFd/themes/core/static/js/CTFd.js
CTFd/themes/core/templates/base.html

* Pass the CTF start and end unix timestamps into the frontend
* Starts work on #447

Get start and end unix timestamps in base.html and install in CTFd.js

---

CTFd/api/v1/challenges.py
CTFd/schemas/awards.py
CTFd/schemas/config.py
CTFd/schemas/files.py
CTFd/schemas/flags.py
CTFd/schemas/hints.py
CTFd/schemas/notifications.py
CTFd/schemas/pages.py
CTFd/schemas/submissions.py
CTFd/schemas/tags.py
CTFd/schemas/teams.py
CTFd/schemas/unlocks.py
CTFd/schemas/users.py
CTFd/utils/config/__init__.py
tests/api/v1/test_teams.py
tests/api/v1/test_users.py

* Properly load schemas specified by their key string
* Add test for UserSchema 
* Prevent users without teams from interacting with challenges if the CTF is in Team Mode

Properly load schemas specified as strings

---

CTFd/schemas/teams.py
CTFd/schemas/users.py
CTFd/themes/admin/static/js/style.js
CTFd/themes/admin/templates/teams/team.html
CTFd/themes/core/templates/teams/private.html
populate.py
tests/api/v1/test_teams.py
tests/api/v1/test_users.py

* Fix admin's modifying their own team or own settings
* Fix some links not working in the admin panel
* Fix extensions with an extra space in `populate.py`

Some 2.1.0a1 bugfixes

---

CONTRIBUTING.md
README.md

* Add `SECRET_KEY` instructions to `README.md` for `docker-compose`
* Add a basic `CONTRIBUTING.md`

Documentation improvements

---

CTFd/utils/exports/__init__.py

* Force `db.create_all` to happen for imports on `sqlite` or on failure to create missing tables
* Force `ctf_theme` to be set to `core` in imports in case a theme is missing from the import or the instance

Force db.create_all to happen for imports on sqlite. 

---

CTFd/utils/initialization/__init__.py

* No longer incur Tracking hits on theme files or custom CSS

Don't insert or check Tracking on static files or custom CSS

---

CTFd/themes/admin/static/js/style.js

* Fixes some modal close buttons not working in the admin panel

Fix modal close buttons not working

---

CTFd/teams.py
tests/teams/test_auth.py

* Ratelimit team join attempts
* Team joins are not particularly a risk as being on a team does not grant any specific ability besides being able to submit challenges.

Ratelimit team join attempts

---

CTFd/views.py
tests/test_views.py

* Fix issue with downloading files after CTF end when view_after_ctf is enabled

Fixing issue downloading files when view_after_ctf is enabled

---

CTFd/admin/challenges.py
CTFd/admin/teams.py
CTFd/admin/users.py
CTFd/themes/admin/templates/modals/challenges/solves.html
CTFd/themes/admin/templates/teams/team.html
CTFd/themes/admin/templates/users/user.html

* Sort solves in admin challenge view by date
* Link to appropriate user and challenge in team, user, and challenge pages

Challenge team mode improvements

---

CTFd/auth.py

* Redirect to `/teams/new` instead of `/challenges` after the user registers in team mode

Redirect to /teams/new after user registers if in team mode

---

CTFd/api/v1/teams.py
CTFd/themes/admin/static/js/teams/actions.js
CTFd/themes/admin/templates/teams/team.html
tests/api/v1/teams/test_team_members.py

* Change `/api/v1/teams/[team_id]/members` from taking `id` to `user_id`.
* Not even the admin panel was using this endpoint so doesn't seem that drastic of a change
* Add UI to handle team member removal

Add UI code to handle team member removal

---

docker-compose.yml

Make ctfd user usable for mysql connection

---

CTFd/api/v1/awards.py

* Clear standings on award creation and deletion

Clear standings on award creation and deletion

---

docs/conf.py
docs/index.rst
docs/scoring.rst

* Bump docs version to 2.1.3.
* Add documentation on scoreboard integrations. 
* Add logo to documentation.

Docs scoring page

---

docs/scoring.rst

* Add MLC section and then cite from CTFTime.

Minor docs fix

---

Dockerfile

* Switch `Dockerfile` from `python:2.7-alpine` to `python:3.7-alpine`
* Closes #1004 
* Starts the ground work for #820

Switch Dockerfile from python:2.7-alpine to python:3.7-alpine

---

populate.py

* Fix `populate.py` from using an `oauth_id` twice.

Don't reuse used oauth_ids in populate.py

---

populate.py

* Make `populate.py` configurable from command line

Add argparse to populate.py and fix some lints

---

CTFd/models/__init__.py
CTFd/utils/humanize/numbers.py
tests/utils/test_humanize.py

* Fix scoreboard place ordinalization in Python 3
* Extract ordinalization code to `CTFd.utils.humanize.numbers.ordinalize`.

Fix place ordinal calculation

---

tests/utils/test_events.py

* Fix flaky tests that require redis which were occasionally failing

Attempt to fix randomly failing tests

---

CTFd/admin/teams.py
CTFd/admin/users.py
CTFd/themes/admin/templates/users/users.html
tests/admin/test_users.py

* The CTF admins can now search for users by an IP address
This PR fixes #1054

Add feature to search users by IP address

---

tests/helpers.py
tests/utils/test_events.py

* Fix flaky redis tests
* Add a random integer helper for tests

Flaky redis events tests

---

CTFd/schemas/users.py
tests/api/v1/test_users.py
tests/users/test_profile.py

* Require password for user email changes

Require password for email change

---

CTFd/api/v1/challenges.py
tests/api/v1/test_challenges.py

* Challenges properly get solve count during freeze time
* Closes #1092

1092 fix solve count leak during freeze

---

wsgi.py

* Fixes `flask run` debug server by not monkey patching in `wsgi.py`
* Closes #1099

Fix flask run by not monkey patching for gevent in wsgi.py

---

CTFd/utils/initialization/__init__.py

* Avoid exception on sessions without a valid user and force logout

Avoid exception on session without a valid user and force logout

---

Dockerfile

* Switch `Dockerfile` from `python:2.7-alpine` to `python:3.7-alpine`
* Closes #1004 
* Starts the ground work for #820

Python 3 dockerfile

---

CTFd/auth.py
CTFd/teams.py
CTFd/themes/admin/templates/configs/accounts.html
CTFd/themes/core/templates/teams/join_team.html
CTFd/themes/core/templates/teams/new_team.html
tests/oauth/test_teams.py
tests/teams/test_teams.py

* Implements team size limits
* Closes #1006

Team size limit

---

CTFd/utils/helpers/__init__.py
CTFd/utils/initialization/__init__.py
tests/utils/test_updates.py
webpack.config.js

* Use a custom `url_for` function in themes
* Modify webpack and yarn to generate development and production js
* Fix `test_update_check_ignores_downgrades`

Seperate dev and prod static assets

---

CTFd/utils/email/__init__.py
CTFd/utils/email/mailgun.py
CTFd/utils/email/smtp.py
CTFd/utils/formatters/__init__.py
tests/utils/test_formatters.py

* Closes #1130
* Adds subject parameter to sendmail functions
* Adds a safe string interpolation function
* http://lucumr.pocoo.org/2016/12/29/careful-with-str-format/

Add subject control to sendmail()

---

CTFd/views.py
tests/users/test_setup.py

Verify admin information during setup process

---

.travis.yml
Makefile
package.json

* Add `yarn verify` command to verify that compiled assets are the same as what would be generated

Verify webpack generated output

---

CTFd/config.py
CTFd/events/__init__.py
tests/test_config.py

* Closes #1078 
* Add `SERVER_SENT_EVENTS` config value to control whether Notifications are enabled

Add SERVER_SENT_EVENTS config value

---

CTFd/themes/admin/templates/base.html

* Add link to help.ctfd.io to the right side of the admin navbar

Add a link to help.ctfd.io to right side of admin navbar

---

.travis.yml
CTFd/auth.py

Prevents users from submitting all whitespace for their password and subsequently having an empty password.

Strip password before length check

---

CTFd/themes/core/templates/login.html
CTFd/themes/core/templates/register.html
CTFd/themes/core/templates/teams/team_enrollment.html
CTFd/utils/config/integrations.py
CTFd/utils/initialization/__init__.py

* Closes #1063 
* Hide MLC related buttons if the integration hasn't been configured

Only show MLC button if MLC is enabled in config

---

CTFd/api/v1/teams.py
CTFd/models/__init__.py
tests/api/v1/teams/test_scoring.py
tests/api/v1/test_challenges.py
tests/api/v1/user/test_challenges.py
tests/api/v1/users/test_scoring.py

* Fixes place from being visible in the self API endpoints while scores are hidden
* Add score and place to team API endpoints

Fix place visible during scores visible

---

CTFd/plugins/dynamic_challenges/__init__.py
CTFd/plugins/dynamic_challenges/assets/view.js
CTFd/themes/core/templates/users/public.html
tests/challenges/test_dynamic.py

* Closes #1043, #1166, #1177
* This consolidates some code for updating challenges to remove an error where updating a challenge could change the challenge's value incorrectly

Closes #1043, #1166, #1177

---

CTFd/themes/admin/templates/configs/appearance.html

Allow ctf description changes

---

CHANGELOG.md
CTFd/__init__.py
docs/conf.py
package.json

2.2.1 / 2020-01-04
**General**
* Fix issue preventing admins from creating users or teams
* Fix issue importing backups that contained empty directories

Mark 2.2.1

---

CTFd/teams.py

* Fix error when joining teams with a size limit

Fix error with invalid team information and team size limits

---

CTFd/auth.py
CTFd/utils/email/__init__.py

* Adds an email notification for password resets

Add a password change notification email

---

CTFd/plugins/dynamic_challenges/assets/view.html

* Fixes hint loading for dynamic challenges

Fix dynamic challenge hint loading

---

CTFd/themes/admin/templates/configs/appearance.html
CTFd/themes/core/templates/base.html
CTFd/utils/initialization/__init__.py
CTFd/views.py
migrations/versions/a03403986a32_add_theme_code_injections_to_configs.py
tests/test_themes.py

* Remove custom css in favor of header and footer injection into themes
* Closes #1235

1231 theme code injection

---

CTFd/themes/admin/templates/configs/email.html
CTFd/utils/email/__init__.py
CTFd/views.py
migrations/versions/1093835a1051_add_default_email_templates.py
tests/users/test_auth.py

* Allow admins to control the content of emails sent by CTFd
* Closes #1002

Customizeable outgoing emails

---

CTFd/auth.py
CTFd/themes/admin/templates/configs/email.html
CTFd/utils/email/__init__.py
CTFd/views.py
migrations/versions/1093835a1051_add_default_email_templates.py
tests/utils/test_email.py

* Closes #1239 
* Adds email variables for successful account registration and updates migration

Email variables documentation

---

CTFd/auth.py

* Prevents user from confirming their account twice

Prevent double confirmations from happening

---

CTFd/auth.py
CTFd/themes/admin/templates/configs/settings.html
CTFd/utils/config/integrations.py
CTFd/utils/config/visibility.py

* Adds a setting to registration visibility to allow for MLC registration while registration is disabled

Add setting to allow MLC registration only

---

CTFd/views.py

* Fix setting theme color from the setup flow

Fix setting theme color from the setup flow

---

CTFd/api/v1/statistics/users.py

* Set UserStatistics route to be admins_only

Set UserStatistics route to be admins_only

---

CTFd/themes/core/templates/base.html
CTFd/utils/initialization/__init__.py

* Use `authed` function to check if user is authed in `base.html`

Use authed function to check if user is authed in base.html

---

CTFd/themes/admin/templates/configs/settings.html

* Makes `Account Visibility` subtext clearer by explaining the `Private` setting

Closes #1305

---

CTFd/utils/initialization/__init__.py

* Bump max log file size to 10 MB and fix log rotation on RotatingFileHandler
* Closes #1302

Add fix for logrotation

---

Dockerfile

**Environment**:
- CTFd Version/Commit:
- Operating System:
- Web Browser and Version:
**What happened?**
**What did you expect to happen?**
Let the container lighter!
**How to reproduce your issue**
**Any associated stack traces or error logs**
-----------------
I feel sorry about my English

Questions about optimizing Dockerfile play

---

CTFd/api/v1/unlocks.py
tests/api/v1/user/test_hints.py

* Prevent a hint from being unlocked twice
* Closes  #1301

Prevent accidental double unlocks

---

.github/workflows/lint.yml

* Starts work on migrating from Travis CI to Github Actions

Add Github Action for lint

---

.eslintrc.js
package.json

* Adds a `yarn lint` command that runs `eslint`
* Starts work on #1245

Add eslint command to yarn

---

CTFd/utils/uploads/uploaders.py

Fix file downloads in Windows

---

CTFd/admin/challenges.py
CTFd/themes/admin/templates/challenges/challenges.html
requirements.txt

* Copies challenge searching functionality from Users searching

Add basic challenge searching functionality

---

requirements.txt

* Pin banal==0.4.2 because of https://github.com/pudo/banal/issues/5

Pin banal==0.4.2 because of https://github.com/pudo/banal/issues/5

---

CTFd/admin/teams.py
CTFd/themes/admin/templates/teams/teams.html

* Make the admin panel team searching use a pagination object instead of custom searching

Admin teams pagination

---

CTFd/admin/challenges.py
CTFd/themes/admin/templates/challenges/challenges.html

* Show total searched results for Admin Panel searching. This doesn't use a Pagination object b/c Admin Panel challenges doesn't paginate.

Show search results on challenge search

---

CTFd/admin/users.py
CTFd/themes/admin/templates/users/users.html

* Make Admin Panel user searching use a Pagination object

Admin users pagination

---

CTFd/__init__.py
CTFd/admin/__init__.py
CTFd/themes/admin/templates/configs/appearance.html
CTFd/themes/admin/templates/reset.html
populate.py
tests/admin/test_config.py

* Improve Reset functionality by allowing admins to pick what data they'd like to reset
* Closes #1355

Add a basic layout for improved table granular reset

---

CTFd/models/__init__.py

* Remove the duplicated `get_config` function from `CTFd/models`

Remove duplicated get_config from models and import before usage

---

CTFd/utils/initialization/__init__.py
tests/teams/test_teams.py
tests/users/test_users.py

* Extract the banning function from the IP tracking code to start moving it into cache

Extract user/team banning code into its own initialization function

---

CTFd/admin/submissions.py

* Fix `url_for` call for Admin Panel submission pagination

Fix url_for for admin panel submission pagination

---

.dockerignore

* Add `node_modules/` to `.dockerignore`

Add node_modules/ to .dockerignore

---

CTFd/config.py

* Add `SQLALCHEMY_ENGINE_OPTIONS` to `config.py` to specify a slightly higher default `max_overflow`

Add SQLALCHEMY_ENGINE_OPTIONS with a slightly higher default max_overflow

---

CTFd/utils/initialization/__init__.py

* Fix an issue where session id no longer exists but the server thinks the user is still authed

Fix an issue where session id no longer exists

---

CTFd/themes/admin/templates/configs/email.html

unable to save changes in admin panel for Account Registration email

admin theme successful confirmation email fix

---

CTFd/api/v1/files.py
tests/api/v1/test_files.py

Fixed an issue in CTFd API: CTFd/api/v1/files.py was not deleting files.

Fix file deletion. Related to #1393

---

Makefile
development.txt
requirements.txt

* Bump boto3 version to 1.13.9

Bump boto3 version to 1.13.9 and install pipdeptree for development

---

CTFd/plugins/flags/__init__.py

* Catch an exception where a user supplied regex Flag can fail to parse
* Starts on #1425

Catch situation where Regex flag fails

---

CTFd/utils/exports/__init__.py

Reverting this because for some reason it looked like some files were missing while testing this against the debug server. Could be related to the fact that the debug server is threaded itself. Regardless this did not solve the problem I was hoping it would. 
I haven't confirmed whether this is a problem under gunicorn.

Revert "Use a ThreadPoolExecutor to concurrently store files dut string import (#1427)"

---

CHANGELOG.md
CTFd/__init__.py
docs/conf.py
package.json

2.4.3 / 2020-05-24
**Miscellaneous**
* Notifications/Events endpoint will now immediately send a ping instead of waiting a few seconds.
* Upgrade `gunicorn` dependency to `19.10.0`
* Upgrade `boto3` dependency to `1.13.9`
* Improve `import_ctf()` reliability by closing all connections before dropping & recreating database
* Close database session in IP tracking code in failure situations to avoid potential dangling database connections
* Don't allow backups to be imported if they do not have a `db` folder
* Change `import_ctf()` process slightly to import built-in tables first and then plugin tables
* Handle exception where a regex Flag is invalid
**API**
* File deletion endpoint (`DELETE /api/v1/files/[file_id]`) will now correctly delete the associated file …

Mark 2.4.3

---

CTFd/api/v1/users.py
CTFd/utils/security/auth.py
CTFd/utils/security/signing.py
CTFd/utils/user/__init__.py
tests/utils/test_sessions.py

* Use a session invalidation strategy inspired by Django. https://docs.djangoproject.com/en/3.0/topics/auth/default/#session-invalidation-on-password-change
* Closes #1430

Add a session invalidation strategy inspired by Django

---

CTFd/utils/__init__.py
requirements.txt
tests/test_views.py

Switch from mistune to cmarkgfm

---

.github/workflows/tests.yml
Dockerfile
docker-entrypoint.sh

1215 dockerfile improvements

---

CTFd/teams.py
CTFd/themes/core/templates/teams/teams.html
CTFd/themes/core/templates/users/users.html
CTFd/users.py

* Replace user facing pagination with Flask SQLAlchemy Pagination objects
* Closes #1353
I think this is a big improvement but I feel like this is harder to create a theme construct around.

User pagination pages

---

CTFd/constants/config.py
CTFd/constants/plugins.py
CTFd/themes/core/templates/base.html
CTFd/utils/initialization/__init__.py

Create the `Configs` and `Plugins` classes to access in Jinja
Work on #1234

Start grouping logic into constants classes

---

CTFd/plugins/challenges/__init__.py
CTFd/plugins/dynamic_challenges/__init__.py
CTFd/plugins/flags/__init__.py
tests/users/test_challenges.py

* Update challenge plugins and flag plugins to raise and catch exceptions for flag error messages
* Closes #1425

Update challenge plugins and flag plugins to have exception messages

---

CTFd/config.py
CTFd/plugins/challenges/__init__.py
CTFd/plugins/dynamic_challenges/__init__.py

* Convert Challenge plugin static methods into class methods
* Copy the create, read, update, attempt, solve, fail methods into the BaseChallenge class so that they can be re-used between challenge plugins

Reorganize challenge plugins

---

.github/workflows/lint.yml
.github/workflows/mysql.yml
.github/workflows/postgres.yml
.github/workflows/sqlite.yml
.github/workflows/tests.yml
.travis.yml
docs/deployment.rst

* Clarifies the position on supporting Postgres and removes Postgres from the main test suite
* Closes #973

Seperate out postgres tests and clarify postgres support

---

CTFd/api/v1/challenges.py
CTFd/themes/core/templates/challenge.html
CTFd/utils/humanize/words.py
CTFd/utils/initialization/__init__.py

* Display current attempts in challenge view when max attempts is enabled
* Closes #1477

Display current attempts in challenge view when max attempts is enabled

---

.github/ISSUE_TEMPLATE.md
CHANGELOG.md
CONTRIBUTING.md
CTFd/plugins/dynamic_challenges/README.md
Makefile
README.md

* Require that markdown files are linted by prettier

Lint markdown and require markdown changes to pass prettier

---

CTFd/api/v1/awards.py
CTFd/api/v1/challenges.py
CTFd/api/v1/config.py
CTFd/api/v1/files.py
CTFd/api/v1/flags.py
CTFd/api/v1/helpers/models.py
CTFd/api/v1/hints.py
CTFd/api/v1/notifications.py
CTFd/api/v1/pages.py
CTFd/api/v1/submissions.py
CTFd/api/v1/tags.py
CTFd/api/v1/teams.py
CTFd/api/v1/unlocks.py
CTFd/api/v1/users.py

* Works on #1318 
* Adds searching and filtering to most of the bulk API endpoints
* Adds documentation on the GET parameters used to conduct searches

Add API searching and filtering

---

CTFd/themes/admin/templates/modals/teams/addresses.html
CTFd/themes/admin/templates/modals/users/addresses.html
CTFd/themes/admin/templates/teams/team.html
CTFd/themes/admin/templates/users/user.html
CTFd/utils/countries/__init__.py
CTFd/utils/countries/geoip.py
CTFd/utils/initialization/__init__.py
populate.py
requirements.txt

* Adds support for looking up countries by IP address. 
* Shows country and flag for a user/team's IP addresses in the admin panel
* Adds support for `GEOIP_DATABASE_PATH` in config.py
* Closes #1115

Lookup the respective country for IP addresses in the admin panel

---

CTFd/api/v1/config.py

* Change `/api/v1/config/<config_key>` to return properly structured data
* Closes #1506

Change /api/v1/config/<config_key> to return structured data

---

CTFd/forms/teams.py
CTFd/forms/users.py
CTFd/teams.py
CTFd/themes/admin/templates/teams/teams.html
CTFd/themes/core/templates/teams/teams.html
CTFd/themes/core/templates/users/users.html
CTFd/users.py

* Add account searching to the user facing side of CTFd
* Closes #1354

Add account searching to the user facing side

---

.github/workflows/lint.yml

* Lint `Dockerfile` and `docker-compose.yml`
* Closes #1458

Add Hadolint to Github Lint action

---

development.txt

* Bump codecov to 2.1.7 to fix coverage reports

Bump codecov to 2.1.7

---

CTFd/cache/__init__.py
CTFd/constants/teams.py
CTFd/constants/users.py
CTFd/utils/user/__init__.py

* Cache accesses of `User.place` and `User.score` in the user attrs wrapper via Jinja

Properly cache User.place and User.score constants

---

CTFd/utils/security/sanitize.py

* Allow bootstrap data attributes through the HTML sanitizer

Allow bootstrap data attributes through the HTML sanitizer

---

CTFd/themes/admin/templates/challenges/new.html

* Fix unclickable label in challenge creation ui

Fix unclickable label in challenge creation ui

---

CTFd/utils/security/sanitize.py

* Re-allow HTML comments in sanitized HTML

Allow comments in HTML

---

CTFd/admin/pages.py
tests/admin/test_pages.py

* Fix previewing pages when page attributes are set

Fix issue with previewing certain pages

---

CTFd/schemas/hints.py

* Fix regression for creating hints via ctfcli
See #1582 for details. 
Closes https://github.com/CTFd/ctfcli/pull/20.

Fix regression in creating hints via API

---

CTFd/teams.py
CTFd/themes/core/templates/teams/private.html
CTFd/themes/core/templates/teams/public.html

* Fix team pages to use the core errors alert component
* Closes #1585

Make team profile pages use the shared errors component

---

CTFd/themes/admin/templates/challenges/challenge.html

* Update icon for link to correct submissions to `fa-tasks`

Update icon for link to correct submissions in challenge page

---

CTFd/cache/__init__.py
CTFd/constants/__init__.py
CTFd/constants/static.py
CTFd/scoreboard.py
CTFd/themes/core/templates/scoreboard.html
CTFd/utils/initialization/__init__.py
tests/api/v1/test_scoreboard.py

* Make scoreboard caching only cache the score table instead of the entire page
* Closes #1584
Hold this for v3.1

Make scoreboard caching only cache the score table

---

CTFd/utils/helpers/models.py
tests/admin/test_submissions.py

* Fix submission searching in Admin Panel

Fix submission search

---

CTFd/themes/core/templates/setup.html

* Fix a potential issue where setup could not be completed b/c next buttons were unclickable

Fix potential issue preventing a user from finishing setup

---

CTFd/themes/admin/templates/teams/team.html
CTFd/themes/admin/templates/teams/teams.html
CTFd/themes/admin/templates/users/user.html
CTFd/themes/admin/templates/users/users.html
CTFd/themes/core/templates/teams/private.html
CTFd/themes/core/templates/teams/public.html
CTFd/themes/core/templates/teams/teams.html
CTFd/themes/core/templates/users/private.html
CTFd/themes/core/templates/users/public.html
CTFd/themes/core/templates/users/users.html

* Add rel=noopener to external links to prevent tab napping attacks

Add rel=noopener to external links

---

CHANGELOG.md

* Add info about custom fields to the themes CHANGELOG

Add info about custom fields to the themes CHANGELOG

---

CTFd/forms/email.py
CTFd/themes/admin/templates/modals/mail/send.html

Fixing issue #1639 , bug that prevented email from being sent.
Applied suggested fixes from @ColdHeat , tested it on my setup, works for me.

Fix for email send issue

---

package.json
yarn.lock

* Bump @babel/polyfill version to 7.11.5

bump @babel/polyfill version to 7.11.5

---

CTFd/themes/admin/templates/base.html

fix [this](https://github.com/CTFd/CTFd/issues/1697).

fix link name

---

CTFd/config.py

* Override the `MAIL_SERVER` config with the `TESTING_MAIL_SERVER` envvar during tests

Set MAIL_SERVER during testing to use the TESTING_MAIL_SERVER envvar

---

CTFd/plugins/flags/assets/regex/create.html

* Adds examples for regex flags in the flag creation form

Add examples for regex flags

---

export.py
import.py
manage.py

* Add `import_ctf` and `export_ctf` commands to `manage.py`
* Deprecate `import.py` and `export.py`
* Works on #1629

Add import export commands to manage.py

---

CTFd/themes/core/templates/challenge.html

* Fixed issue where the current attempt count would have a typo
* Fixed issue where the max attempts for a challenge would not show if it was set to 1
* Works on #1655

Max Attempts improvements in challenge.html

---

CTFd/utils/updates/__init__.py

* Increase timeout for update check from 0.1 seconds to 3 seconds
* Closes #1678

Increase timeout for update check

---

CTFd/forms/setup.py
CTFd/themes/core/templates/setup.html
CTFd/views.py

* Adds index page banner to the setup flow
* Closes #1658

Add banner to setup

---

CTFd/api/v1/teams.py
CTFd/forms/config.py
CTFd/themes/admin/templates/configs/accounts.html
tests/api/v1/test_teams.py

* Add a Config setting for disabling team disbanding
* Closes #1746

Add a config setting to disable public team disbanding

---

CHANGELOG.md
CTFd/auth.py
CTFd/teams.py
CTFd/themes/core/templates/teams/private.html
CTFd/utils/decorators/__init__.py
tests/users/test_fields.py

* Update CHANGELOG 
* Add `registered_only` decorator
* Make team invites redirect to `/register` if you're unauthed

Miscellaneous Fixes

---

CHANGELOG.md
CTFd/schemas/teams.py
CTFd/schemas/users.py

- Fixed an issue where Users/Teams could be created with a null password through the Admin Panel

Require passwords on accounts

---

CHANGELOG.md
CTFd/__init__.py
CTFd/api/v1/unlocks.py
tests/api/v1/user/test_hints.py
tests/teams/test_hints.py

- Fixed an issue where Users could not unlock hints

Mark 3.2.1

---

CTFd/api/v1/users.py

* Don't allow admins to accidentally delete themselves

Don't allow admins to delete themselves

---

development.txt
requirements.in
requirements.txt

* Bump lxml to 4.6.2
* Bump pip-compile to 5.4.0

Bump some Python dependencies

---

CTFd/schemas/pages.py

* Use right length in Page title validator

Fix incorrect schema validator

---

CTFd/plugins/__init__.py
tests/test_plugin_utils.py

* Fix issue where Page URLs were relative in the navbar
* Closes #1797

Fix issue where page URLs were relative

---

CTFd/api/v1/users.py
tests/api/v1/test_users.py
tests/api/v1/users/test_users.py

* Fix an exception that occurred when demoting an Admin user
* Fix the response from the above request from returning a list instead of a dict
* Closes #1794

Fix exception occurring on Admin demotion

---

CTFd/forms/config.py
CTFd/teams.py
CTFd/themes/admin/templates/configs/accounts.html
tests/teams/test_teams.py

* Add ability for admins to disable public team creation
* Closes #1364

Add team creation disable configuration

---

CTFd/themes/admin/templates/configs/accounts.html

* Fix default team_creation representation value in the config page

Fix default team_creation representation value in the config page

---

CTFd/forms/auth.py
CTFd/themes/core/templates/confirm.html
CTFd/utils/email/__init__.py
tests/users/test_auth.py
tests/utils/test_email.py

* Change the default emails slightly and rework confirmation email page to make some recommendations clearer
* Works a little more on #1002

1002 improve email content

---

CTFd/themes/admin/templates/teams/teams.html
CTFd/themes/admin/templates/users/users.html

* Fixes some issues reported by [curlylint](https://github.com/thibaudcolas/curlylint).
Not sure if these were reported by the underlying jinjalint or curlylint's fixes but I think there's value in having something like this in the automated testing.

Fix some template issues reported by curlylint

---

CTFd/admin/submissions.py
CTFd/constants/config.py
CTFd/themes/admin/templates/submissions.html
CTFd/utils/modes/__init__.py

* Links directly to users who submitted something in the submissions page if the CTF is in teams mode. 
* Closes #1813

Link directly to users from the submissions page in teams mode

---

CTFd/plugins/migrations.py

* Set plugin migration version after successful migrations
* Closes #1763

Set plugin migration version after a successful migration

---

CHANGELOG.md
CTFd/config.py
CTFd/utils/security/sanitize.py
requirements.in
requirements.txt

* Use `pybluemonday` instead of `lxml` for html sanitization
* Fix boolean optional configs in `config.py`
* Closes #1835

Use pybluemonday instead of lxml for html sanitization

---

CTFd/api/v1/challenges.py
tests/api/v1/test_challenges.py

fix: Ensure hidden users see their own solves

---

CTFd/api/v1/challenges.py
tests/api/v1/test_challenges.py

Merge in PR fixes

---

CHANGELOG.md
CTFd/themes/core/templates/teams/private.html
CTFd/themes/core/templates/teams/public.html
CTFd/themes/core/templates/users/private.html
CTFd/themes/core/templates/users/public.html

- Change users/private.html, users/public.html to show awards before a user gets a solve
- Change teams/private.html, teams/public.html to show awards before a team gets a solve

Fix user profiles not showing awards before an account gets a solve

---

CHANGELOG.md
CTFd/utils/initialization/__init__.py

* Make expired token error message more useful

Make expired token error message more useful

---

CHANGELOG.md

It's 2021 now, time flies haha

Fix wrong date for v3.3.0 changelog.

---

tests/test_themes.py

use different directories for different tests

---

Dockerfile
docker-entrypoint.sh
ping.py

* Replaces `mysqladmin ping` with a custom script
* Closes #725

ping database with python instead of mysql client

---

requirements.in
requirements.txt

* Bump version of pybluemonday

Bump pybluemonday version

---

tests/constants/time.py
tests/helpers.py
tests/utils/test_ctftime.py

A starting PR for issue #928. Want to confirm the structure of the context manager and enums before updating all the tests.

Ctftime test context #928

---

CTFd/themes/admin/templates/challenges/new.html

* Widen the challenge creation form to make it easier to show longer challenge types

Widen the challenge creation form to make it easier to show longer challenge types

---

CTFd/auth.py

* Handle an edge case where users try to login but were logged in through an authentication provider

Handle edge case where users have a null password

---

CTFd/utils/security/sanitize.py
requirements.in
requirements.txt

* Bump pybluemonday version to 0.0.6 
* Allow HTML comments in sanitized output
* Closes #1906

Bump pybluemonday version to 0.0.6 

---

CTFd/utils/config/integrations.py

* Add fix for MLC configs defined in config.ini/config.py

Add fix for MLC configs in config.ini

---

CTFd/themes/admin/templates/modals/users/addresses.html
CTFd/utils/countries/geoip.py
CTFd/utils/initialization/__init__.py
requirements.in
requirements.txt

* Closes #1872 
* IP Addresses in the Admin Panel will now show the city of the IP address as well as the country

Switch python-geoacumen to python-geoacumen-city

---

CTFd/themes/admin/templates/teams/team.html

* Show a team member's individual score in the admin panel

Show a team member's individual score in the admin panel

---

CTFd/admin/users.py

Fix issue where admins can't load a user's admin panel page when in teams mode

---

CTFd/views.py

@ColdHeat and I discussed this via email. Simply sends the page title from the database over to the view.

Send title of Page to view

---

CTFd/schemas/users.py
tests/api/v1/test_users.py

* Prevent users from PATCH'ing their team id

Validate that a user can't patch their team id

---

CTFd/themes/core/templates/setup.html
CTFd/views.py

* Closes #1935 
* Add text to make it clearer what each user mode is during setup
~Might be able to also do https://github.com/CTFd/CTFd/issues/1899~ Can't solve this  one simply so will push it to another PR.

Add text to make it clearer what each user mode is

---

CTFd/schemas/teams.py

* Only allow team members to be promoted to captain

Only allow team members to be promoted to captain

---

CTFd/auth.py
CTFd/forms/auth.py
CTFd/forms/users.py
CTFd/themes/admin/templates/config.html
CTFd/themes/admin/templates/configs/security.html
CTFd/themes/core/templates/register.html
tests/users/test_auth.py

* Closes #1895 
* Add a registration password to account creation (ignoring SSO or API based account creation)

WIP: Add registration password

---

CTFd/themes/admin/templates/configs/security.html

* Fix form render with registration code in Config page

Fix simple css issue

---

requirements.in
requirements.txt

Bump pybluemonday to 0.0.7

---

CTFd/admin/__init__.py
CTFd/forms/config.py
CTFd/utils/csv/__init__.py

* Closes #1940
* Create Scoreboard CSV export with support for custom fields
* Create Users CSV export with support for custom fields
* Create Teams CSV export with support for custom fields

Improved CSV exports

---

CTFd/utils/csv/__init__.py

Small fixes from making CSV examples

---

CHANGELOG.md

Add 3.4.0 CHANGELOG as unreleased

Add 3.4.0 CHANGELOG as unreleased

---

CTFd/plugins/challenges/assets/view.html
CTFd/plugins/dynamic_challenges/assets/view.html

* Simplify view.html in the provided challenge plugins to better support the eventual core-beta theme

Simplify view.html in provided challenge types to support core-beta

---

CTFd/themes/admin/templates/configs/backup.html

* Add instructions for CSV importing

Add guidance for CSV imports

---

CTFd/themes/admin/templates/modals/users/create.html

Fixed #1985 by changing the id

Fix non-clickable checkbox label in user creation form in Admin side

---

CTFd/utils/security/auth.py

Fixes https://github.com/CTFd/CTFd/issues/1990.

Make login sessions permanent

---

CTFd/api/__init__.py

Hi 👋 
This PR is adding a documentation to clarify the behaviour reported in #1974, #2020 and [How to use API tokens?](https://community.majorleaguecyber.org/t/how-to-use-api-tokens/255?).
- https://flask-restx.readthedocs.io/en/latest/swagger.html#documenting-authorizations
- https://swagger.io/docs/specification/2-0/authentication/
- https://github.com/OAI/OpenAPI-Specification/blob/main/versions/2.0.md#security-scheme-object

Document API authentication

---

CTFd/api/v1/challenges.py
CTFd/forms/config.py
CTFd/themes/admin/templates/configs/accounts.html

* Allow submissions per minute ratelimit to be configurable
* Closes #2014

Add a way to configure challenge attempt ratelimiting

---

CTFd/cache/__init__.py
CTFd/utils/user/__init__.py

* Fix an issue where a user's session isn't cleared properly after they are deleted by an admin
* Closes #1996

Fix issue with clearing user's session after deletion

---

CTFd/utils/uploads/uploaders.py

* Fix boto3 signature to be the correct one as discussed in #1953 and #1882

Fix boto3 s3 signature

---

CTFd/views.py

* Have profile notify user to join/create a team (Closes #2013)

Have profile notify user to join/create a team

---

requirements.in
requirements.txt

Bump cmarkgfm to 0.8.0

---

CTFd/utils/exports/__init__.py

* Fix issues with importing backups that contain Challenge Topics and Custom Fields

Fix importing backups that contain challenge topics and custom fields

---

CTFd/utils/csv/__init__.py

* Fix issue where custom field entries for Users and Teams would be misaligned in the scoreboard CSV export

Fix CSV export columns for team & user fields on scoreboard CSV

---

CTFd/api/v1/teams.py

* Add meta and count field to teams endpoints to make it easier to show graphs

Add meta and count field to teams endpoints to make it easier to show graphs

---

CTFd/admin/__init__.py

* Fix issue where current theme cannot be found in list of themes

Fix issue where current theme cannot be found in list of themes

---

CTFd/themes/admin/templates/base.html
CTFd/themes/core/templates/base.html
tests/users/test_users.py

* Add `userName` and `userEmail` to the CTFd init object in `base.html`
* Closes #2066

Add userName and userEmail to init objects in base.html

---

CTFd/api/v1/teams.py
CTFd/api/v1/users.py

* Improve speed of `/api/v1/teams/me/fails`
* Improve speed of `/api/v1/teams/[team_id]/fails`
* Improve speed of `/api/v1/users/me/fails`
* Improve speed of `/api/v1/users/[user_id]/fails`

Speed improvements

---

CTFd/constants/assets.py
CTFd/utils/__init__.py

* Disable caching of get_asset_json if debug mode

Disable caching of get_asset_json if debug mode

---

CTFd/admin/pages.py
tests/admin/test_pages.py

* Fix page preview so that it accounts for the provided format
* Closes #2089

Fix page preview so that it accounts for the provided format

---

CHANGELOG.md

Add changelog for 3.5.0

---

CHANGELOG.md
CTFd/api/v1/teams.py

* Add meta and count field to `/api/v1/teams/[team_id]/awards` and `/api/v1/teams/me/awards`

Add meta and count field to teams awards endpoints

---

CHANGELOG.md
CTFd/plugins/challenges/assets/view.js
CTFd/plugins/dynamic_challenges/assets/view.js

* Remove some unused functions from the default provided standard & dynamic challenge `view.js` files

Null out some functions in view.js

---

CTFd/api/v1/hints.py

* Fix issue where hint with a free requirement could not be unlocked

Fix issue where hint with a free requirement could not be unlocked

---

CHANGELOG.md
CTFd/themes/core/templates/base.html
tests/teams/test_teams.py

- Add `teamId` and `teamName` to the CTFd init object in `base.html` for easier integration with other JavaScript code

Add teamId and teamName to base.html

---

CHANGELOG.md
CTFd/themes/admin/templates/modals/teams/addresses.html
CTFd/themes/admin/templates/modals/users/addresses.html

Add the possibility to click on a user IP on the admin to search for this IP, as if if were entered in the search field.

[Admin] Add a link on the IP modal to search for a given IP address accross all users.

---

ping.py

* Update ping.py to only print the hostname of the target database

Update ping.py to only print the hostname of the target database

---

CTFd/utils/csv/__init__.py

Added user id and user email fields to the user mode scoreboard csv export as per issue #2133.

Add info to user scoreboard csv

---

CTFd/utils/csv/__init__.py

* Add CSV export for `teams+members+fields` which is teams with fields and their team members with fields
* Closes #2145

Add CSV export for teams+members+fields which is teams with fields and their team members with fields

---

CTFd/utils/exports/__init__.py
manage.py

* Catch all exceptions in import process to report to admin

Catch all exceptions in import process to report to user

---

CTFd/utils/exports/__init__.py

Fix bandit lint

---

CTFd/config.ini
CTFd/config.py
CTFd/plugins/__init__.py

* Properly load `SAFE_MODE` config from environment variable
* Closes #2168

Load SAFE_MODE config from envvar

---

CTFd/config.py

* Don't error out if SAFE_MODE config doesn't exist

Don't error out if SAFE_MODE config doesn't exist

---

CTFd/plugins/migrations.py

* Add mechanism for plugin migrations to get current tables and columns

Add mechanism for plugin migrations to get current tables and columns

---

CTFd/plugins/dynamic_challenges/__init__.py

* Fix issue where dynamic_challenges couldn't load their own migrations

Fix issue with dynamic_challenges migration loading

---

CTFd/themes/admin/templates/base.html
CTFd/themes/core/templates/base.html

* Emit more theme init data using tojson
* Add `teamId` and `teamName` into admin `base.html`

Emit more theme init data using tojson

---

CTFd/models/__init__.py
CTFd/utils/scores/__init__.py
migrations/versions/46a278193a94_enable_millisecond_precision_in_mysql_.py
tests/api/v1/test_scoreboard.py

* Fix issue with scoreboard ordering when an award results in a tie
* Closes #833

Fix issue with scoreboard ordering when an award results in a tie

---

CTFd/themes/admin/templates/modals/teams/create.html
CTFd/themes/admin/templates/modals/teams/edit.html
CTFd/themes/admin/templates/modals/users/create.html
CTFd/themes/admin/templates/modals/users/edit.html
CTFd/themes/admin/templates/reset.html
CTFd/themes/admin/templates/users/users.html

* Fix other issues wih missing autocomplete='off'
* Related to #2158

Fix other issues wih missing autocomplete='off'

---

CTFd/plugins/migrations.py

* Add `names_only` parameter to `get_columns_for_table`

Add names_only parameter to get_columns_for_table

---

CTFd/themes/admin/templates/challenges/challenges.html
CTFd/themes/admin/templates/modals/teams/addresses.html
CTFd/themes/admin/templates/modals/users/addresses.html
CTFd/themes/admin/templates/pages.html
CTFd/themes/admin/templates/scoreboard.html
CTFd/themes/admin/templates/submissions.html
CTFd/themes/admin/templates/teams/team.html
CTFd/themes/admin/templates/teams/teams.html
CTFd/themes/admin/templates/users/user.html
CTFd/themes/admin/templates/users/users.html

Fix display error on mobile devices

Fix display error on mobile devices

---

Dockerfile

Separate docker build in two stages make advantages for discard several binaries, builder, compiler and dev dependencies not needed for production usage.
For transfer python dependencies from first stage to second stage of project, I'm using python venv.
On second stage, only install runtime dependencies and copy source.
Final image reduce size from 648MB for 398MB.

Add support for Docker multi-stage builds

---

CTFd/api/v1/scoreboard.py

* Add int requirement to `/api/v1/scoreboard/top/<count>`

Fix scoreboard detail count parameter

---

Dockerfile

* Set ownership of venv in Dockerfile to 1001

Fix Dockerfile venv

---

CTFd/themes/admin/templates/config.html
CTFd/themes/admin/templates/configs/pages.html
CTFd/utils/initialization/__init__.py
CTFd/views.py
tests/test_views.py

* Adds support for admins to control `robots.txt`
* Closes #2141

Add support for robots.txt

---

CTFd/auth.py
CTFd/schemas/users.py

* Change email whitelist error message to not include the list of allowed domains

Change email whitelist error message to not include the list of allowed domains

---

development.txt
requirements.in
requirements.txt

this fixes #2290, to bump the version down to 0.36.5

bump SQLAlchemy-Utils to version 0.41.0

---

CTFd/forms/teams.py

Was unclear where you had to enter the old password

Confirm Old Team Password 

---

requirements.in
requirements.txt

* Bump pybluemonday version to `0.0.11` to support Python 3.11
* Closes #2301

Bump pybluemonday version to support Python 3.11

---

CTFd/admin/__init__.py
CTFd/themes/admin/templates/configs/security.html
CTFd/utils/config/pages.py

* Add a section in the config panel to configure html sanitization
* `HTML_SANITIZTION` in config.ini can still force sanitization regardless of the database configuration
* Closes #2194

Add a section in the config panel to configure html sanitization

---

CTFd/auth.py
CTFd/forms/config.py
CTFd/themes/admin/templates/configs/accounts.html
tests/oauth/test_users.py
tests/users/test_users.py

* Add a config where Admins can limit the total number of user registrations
* Closes #2308

User registration limit

---

CTFd/themes/core-beta/README.md
CTFd/themes/core-beta/templates/settings.html
CTFd/themes/core-beta/templates/teams/public.html

* Update core-beta to the latest version
Make sure to use a merge commit for this.

Update core beta

---

CTFd/plugins/dynamic_challenges/__init__.py
CTFd/plugins/dynamic_challenges/assets/create.html
CTFd/plugins/dynamic_challenges/assets/update.html
CTFd/plugins/dynamic_challenges/decay.py
CTFd/plugins/dynamic_challenges/migrations/eb68f277ab61_add_func_column_to_dynamic_challenges.py
tests/challenges/test_dynamic.py

* Add linear decay funciton to dynamic value challenges
* Add the ability to choose between decay functions for dynamic value challenges
* Closes #2224 
* Closes #865

Add linear decay function to dynamic challenges

---

docker-entrypoint.sh

* Switch from manage.py to flask cli in docker-entrypoint.sh to get Docker image working again
* Closes #2352

Switch from manage.py to flask cli in docker-entrypoint.sh

---

CTFd/plugins/dynamic_challenges/migrations/eb68f277ab61_add_func_column_to_dynamic_challenges.py

* Fix down revision ID in eb68f277ab61_add_func_column_to_dynamic_challenges.py

Fix down revision ID

---

CTFd/forms/setup.py

Set core-beta as default theme for setup

---

requirements.in
requirements.txt

* Bump pybluemonday to 0.0.12 to support Apple Silicon

Bump pybluemonday to 0.0.12

---

Makefile

* Add usage instructions for make translations-init

Add usage instructions for make translations-init

---

CTFd/plugins/dynamic_challenges/migrations/eb68f277ab61_add_func_column_to_dynamic_challenges.py

* Fix issue in migration with some MySQL versions

Fix eb68f277ab61_add_func_column_to_dynamic_challenges migration

---

CTFd/teams.py

* Allow teams to set their country during registration

Set team country set during registration

---

CTFd/plugins/dynamic_challenges/migrations/b37fb68807ea_add_cascading_delete_to_dynamic_.py
CTFd/plugins/dynamic_challenges/migrations/eb68f277ab61_add_func_column_to_dynamic_challenges.py

* Make dynamic challenge migrations resilient to being applied twice

Make dynamic challenge migrations resilient to being applied twice

---

CTFd/forms/setup.py
CTFd/views.py

* Add visibility settings and some minor settings to setup flow
* Defaults the setup theme to core-beta. Closes #1899

Add visibility settings and some minor settings to setup flow

---

.github/workflows/mysql.yml
.github/workflows/postgres.yml
.github/workflows/sqlite.yml

* Reduce the test Github Action Workflows to only run against the master branch

Reduce the situations when test actions will run

---

CTFd/models/__init__.py
CTFd/utils/csv/__init__.py
tests/models/test_model_utils.py

* Closes #2403 
* Fix issue where polymorphic tables could not be dumped reliabily

Fix issues with CSV exporting

---

CTFd/schemas/users.py

* Show an error when users who don't have a previous password try to set a new password

Show error when a user tries to set their password without a previous password

---

CTFd/schemas/users.py

* Fix issue where NULL password prevented custom fields from being set

Fix issue where NULL password prevented custom fields from being set

---

CTFd/plugins/dynamic_challenges/__init__.py

Fix missing next_id on dynamic challenges

---

CTFd/models/__init__.py
tests/api/v1/teams/test_scoring.py
tests/api/v1/users/test_scoring.py

* Fix issue where the API was not respecting score visibility

Fix issue where the API was not respecting score visibility

---

.github/workflows/lint.yml
Makefile
development.txt
linting.txt

* Add dennis linter for translations

Add linter for translations

---

CTFd/utils/initialization/__init__.py

* Exposes `unix_time_to_utc()` as a Jinja filter

Closes #2416

---

CTFd/api/v1/files.py
CTFd/models/__init__.py
CTFd/utils/uploads/__init__.py
CTFd/utils/uploads/uploaders.py
migrations/versions/5c4996aeb2cb_add_sha1sum_field_to_files_require_.py
tests/api/v1/test_files.py

* Calculate a files sha1sum on upload for future local change detection purposes
* Allow clients to control the location of an uploaded file
* Adds the optional path field to the Uploaders class to control where files get uploaded to
* Closes #1595

File upload improvements

---

CTFd/cache/__init__.py
CTFd/models/__init__.py
CTFd/utils/initialization/__init__.py
Makefile
linting.txt
tests/cache/test_challenges.py
tests/constants/test_constants.py

* Update isort version to 5.13.2
* Disable import ordering in ruff
* Add isort to make lint

Use isort for import order checking

---

CTFd/themes/admin/templates/editor.html
CTFd/views.py

* Default index page name to CTF name

Default index page name to CTF name

---

CTFd/__init__.py

* Tries to address issues where starting CTFd can interfere with an import

Pause CTFd startup when an import is in progress

---

requirements.in
requirements.txt

* Bump boto3 version to 1.34.39

Bump boto3 version

---

CTFd/utils/social/__init__.py
tests/test_share.py

* Show challenge value in social template instead of solve count

Add challenge value in social template

---

CTFd/utils/csv/__init__.py

* Fix issues where types which we did not want to accept as JSON were being processed as JSON in Challenge CSVs

Fix json flag hint import in Challenge CSV

---

CTFd/plugins/dynamic_challenges/__init__.py

Add decay function to `DynamicValueChallenge.read`

---

CTFd/api/__init__.py
CTFd/api/v1/exports.py
CTFd/utils/exports/__init__.py
tests/api/v1/test_exports.py

* Add `POST /api/v1/exports/raw` to download CTFd and CSV exports via the API

Add API endpoint to download exports

---

CTFd/config.ini
CTFd/config.py
CTFd/utils/initialization/__init__.py

* Add setting for CROSS_ORIGIN_OPENER_POLICY

Add setting for CROSS_ORIGIN_OPENER_POLICY

---

CTFd/api/v1/challenges.py

* Fix issue where challenge solves would not respect account visibility

Fix issue where challenge solves would not respect account visibility

---

CTFd/forms/config.py
CTFd/themes/admin/templates/config.html
CTFd/themes/admin/templates/configs/localization.html
CTFd/utils/user/__init__.py

* Add the default_locale config in the Admin Panel to allow admins to configure the default language

Add the default_locale config in the Admin Panel to allow admins to configure the default language

---

CTFd/api/v1/unlocks.py
tests/teams/test_hints.py

Small typo fix in unlocks API endpoint

Fix typo in unlocks API

---

CTFd/models/__init__.py
CTFd/plugins/challenges/__init__.py
CTFd/themes/admin/templates/challenges/create.html
CTFd/themes/admin/templates/challenges/update.html
migrations/versions/4fe3eeed9a9d_add_attribution_to_challenges.py
populate.py

* Add attribution field to Challenges model to support for providing attribution to challenge authors

Add attribution field to Challenges model

---

CTFd/themes/admin/templates/challenges/create.html

This is to keep challenge creation flow simple

Remove attribution from initial challenge creation flow

---

CTFd/models/__init__.py
CTFd/themes/admin/templates/teams/team.html
CTFd/themes/admin/templates/teams/teams.html
CTFd/themes/admin/templates/users/user.html
CTFd/themes/admin/templates/users/users.html

* Display brackets in user facing side of CTFd and Admin Panel
* Adds `user.bracket`, `team.bracket` relationship
* Works on #2530

Display brackets

---

requirements.in
requirements.txt

Bump pybluemonday to 0.0.14

---

CTFd/schemas/teams.py
CTFd/schemas/users.py
tests/api/v1/teams/test_teams.py
tests/api/v1/users/test_users.py

* Allow users & teams to set their password if there is no password set

Allow users & teams to set their password if there is no password set

---

CTFd/plugins/dynamic_challenges/__init__.py

Fix attribution for dynamic challenges

---

.github/workflows/mysql8.yml

* Add MySQL 8.0 to test matrix

Update to add MySQL 8.0 to test matrix

---

CTFd/schemas/teams.py
CTFd/schemas/users.py

* Fix issue where users/teams could set their own bracket after registration

Fix issue where users could set their own bracket after registration

---

CTFd/utils/csv/__init__.py

* Add bracket ID and bracket name to CSV scoreboard for user and team modes

Add bracket ID and bracket name to scoreboard CSV exports

---

CTFd/admin/__init__.py
CTFd/api/v1/exports.py
CTFd/utils/sessions/__init__.py
requirements.in
requirements.txt
tests/admin/test_views.py
tests/api/v1/test_fields.py
tests/api/v1/user/test_admin_access.py
tests/cache/test_challenges.py
tests/oauth/test_redirect.py
tests/teams/test_challenges.py
tests/test_themes.py
tests/test_views.py
tests/users/test_auth.py
tests/users/test_fields.py
tests/users/test_setup.py
tests/utils/test_sessions.py

* Bump Flask to 2.2.5 
* Bump Werkzeug to 2.3.7

Bump Flask to 2.2.5 and Werkzeug to 2.3.7

---

CTFd/constants/languages.py

Add Greek, Finnish, Romanian, Slovenian language constants. 
Swedish is pending while we wait for the translator to upload the language.

Add new language constants (Swedish pending)

---

CTFd/api/v1/flags.py
tests/api/v1/test_flags.py

* Strip static & regex flags of whitespace on creation and deletion
* Closes #851

Update flags to strip static & regex flags on create/update

---

CTFd/constants/teams.py
CTFd/constants/users.py

* Update UserAttrs and TeamAttrs to default values to None instead of erroring

Add default values of None to UserAttrs and TeamAttrs

---

CTFd/admin/challenges.py
CTFd/auth.py
CTFd/cache/__init__.py
CTFd/utils/exports/__init__.py
CTFd/utils/helpers/__init__.py
development.txt

* Fix issue where challenge preview didn't work because ratings weren't loaded
* Bump bandit in tests to 1.8.6

Fix issue where challenge preview didn't work because ratings weren't loaded

---

.github/workflows/mirror-core-theme.yml

This reverts commit 7650447d03b698446da46b3911c145109b46f4bb.

Revert "Try using subtree split to mirror core theme (#2837)"
